.TH "MainWindow" 3 "Wed Mar 15 2023" "OmronPID" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainWindow
.SH SYNOPSIS
.br
.PP
.PP
Inherits QMainWindow\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBperiodicWork\fP ()"
.br
.ti -1c
.RI "void \fBmakePlot\fP ()"
.br
.ti -1c
.RI "void \fBTempCheck\fP ()"
.br
.RI "\fBMainWindow::TempCheck\fP\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainWindow\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBLogMsg\fP (QString str, bool newLine=true)"
.br
.ti -1c
.RI "void \fBfindSeriesPortDevices\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB29\fP of file \fBmainwindow\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MainWindow::MainWindow (QWidget * parent = \fC0\fP)\fC [explicit]\fP"
helpDialog
.PP
plotDialog
.PP
modified '0x0A0A -> ''0x0A00' in part of the first argument in addItem function @ 2023/2/27 by Daisuke Miura\&. This is a display issue on the GUI and has nothing to do with functionality\&.
.PP
Thread for TempCheck mode\&.
.PP
Thread for TempCheck mode\&. Priotity is set to QThread::TimeCriticalPriority
.PP
Thread for Logging\&. Priotity is set to QThread::HighestPriority
.PP
TempCheck counter is set to be 0\&.
.PP
LogStart
.PP
Reserved memory size
.PP
Definition at line \fB33\fP of file \fBmainwindow\&.cpp\fP\&.
.SS "MainWindow::~MainWindow ()"

.PP
Definition at line \fB290\fP of file \fBmainwindow\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void MainWindow::findSeriesPortDevices ()"

.PP
Definition at line \fB325\fP of file \fBmainwindow\&.cpp\fP\&.
.SS "void MainWindow::LogMsg (QString str, bool newLine = \fCtrue\fP)"

.PP
Definition at line \fB307\fP of file \fBmainwindow\&.cpp\fP\&.
.SS "void MainWindow::makePlot ()\fC [slot]\fP"

.PP
Definition at line \fB1608\fP of file \fBmainwindow\&.cpp\fP\&.
.SS "void MainWindow::periodicWork ()\fC [slot]\fP"

.PP
Definition at line \fB1579\fP of file \fBmainwindow\&.cpp\fP\&.
.SS "void MainWindow::TempCheck ()\fC [slot]\fP"

.PP
\fBMainWindow::TempCheck\fP\&. The temperature stores in vtemp_ until the given number is reached\&. A moving average is calculated from these values\&. If this moving average is smaller than the threshold value, it is assumed that there is no temperature change and the Quit function is executed\&. If it is greater than the threshold value, set countTempCheck_ to 0 and exit TempCheck mode\&. Note that this function does not work if the temperature is in the ignore range given setParamters function\&. 
.PP
Definition at line \fB1528\fP of file \fBmainwindow\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OmronPID from the source code\&.
