.TH "md__r_e_a_d_m_e" 3 "Wed Mar 15 2023" "OmronPID" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- OmronPID 
.PP

.SH "Original source code"
.PP
\fCOriginal source code\fP can be get\&. 
.PP
.nf
git clone https://github\&.com/TripletESR/Omron_PID\&.git

.fi
.PP
 The original souce is be abailable in Qt4 or 5\&.
.SH "2023_Qt6 branch"
.PP
In Qt6, this is not available because some functions are obsolute\&. To use it in Qt6, this source code needs to be rewritten\&. The update is developpoing in the 2023_Qt6 branch\&. Now the contents in 2023_Qt6 include some issues, so it is not available\&. 
