.TH "MyQLineEdit" 3 "Wed Mar 15 2023" "OmronPID" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyQLineEdit
.SH SYNOPSIS
.br
.PP
.PP
Inherits QLineEdit\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBShowInt\fP (int)"
.br
.ti -1c
.RI "void \fBShowDouble\fP (double)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBmyqlineedit\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MyQLineEdit::MyQLineEdit ()"

.PP
Definition at line \fB3\fP of file \fBmyqlineedit\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void MyQLineEdit::ShowDouble (double d)\fC [signal]\fP"

.PP
Definition at line \fB15\fP of file \fBmyqlineedit\&.cpp\fP\&.
.SS "void MyQLineEdit::ShowInt (int i)\fC [signal]\fP"

.PP
Definition at line \fB8\fP of file \fBmyqlineedit\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OmronPID from the source code\&.
