.TH "MyThread" 3 "Wed Mar 15 2023" "OmronPID" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyThread
.SH SYNOPSIS
.br
.PP
.PP
Inherits QThread\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBdata_update\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMyThread\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBinterval_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBmythread\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MyThread::MyThread (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.PP
Definition at line \fB3\fP of file \fBmythread\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void MyThread::run ()"

.PP
Definition at line \fB8\fP of file \fBmythread\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int MyThread::interval_"

.PP
Definition at line \fB15\fP of file \fBmythread\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OmronPID from the source code\&.
