.TH "plotdialog.h" 3 "Wed Mar 15 2023" "OmronPID" \" -*- nroff -*-
.ad l
.nh
.SH NAME
plotdialog.h \- The dialog to set parameters of qcustomplot\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br
\fC#include <QMutex>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlotDialog\fP"
.br
.RI "The \fBPlotDialog\fP class\&. "
.in -1c
.SH "Detailed Description"
.PP 
The dialog to set parameters of qcustomplot\&. 


.PP
\fBAuthor\fP
.RS 4
Daisuke Miura 
.RE
.PP
\fBDate\fP
.RS 4
2023/3/9
.RE
.PP
The values of spin boxes are send to the boxes on mainwindow\&.ui\&. 
.PP
Definition in file \fBplotdialog\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OmronPID from the source code\&.
