.TH "PlotDialog" 3 "Wed Mar 15 2023" "OmronPID" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlotDialog \- The \fBPlotDialog\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <plotdialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlotDialog\fP (QWidget *parent=nullptr)"
.br
.RI "\fBPlotDialog::PlotDialog\fP\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdisplayRange_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBPlotDialog\fP class\&. 
.PP
Definition at line \fB22\fP of file \fBplotdialog\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PlotDialog::PlotDialog (QWidget * parent = \fCnullptr\fP)\fC [explicit]\fP"

.PP
\fBPlotDialog::PlotDialog\fP\&. 
.PP
Definition at line \fB8\fP of file \fBplotdialog\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int PlotDialog::displayRange_"

.PP
Definition at line \fB28\fP of file \fBplotdialog\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OmronPID from the source code\&.
