.TH "QCP" 3 "Wed Mar 15 2023" "OmronPID" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QCP
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBResolutionUnit\fP { \fBruDotsPerMeter\fP, \fBruDotsPerCentimeter\fP, \fBruDotsPerInch\fP }"
.br
.ti -1c
.RI "enum \fBExportPen\fP { \fBepNoCosmetic\fP, \fBepAllowCosmetic\fP }"
.br
.ti -1c
.RI "enum \fBSignDomain\fP { \fBsdNegative\fP, \fBsdBoth\fP, \fBsdPositive\fP }"
.br
.ti -1c
.RI "enum \fBMarginSide\fP { \fBmsLeft\fP = 0x01, \fBmsRight\fP = 0x02, \fBmsTop\fP = 0x04, \fBmsBottom\fP = 0x08, \fBmsAll\fP = 0xFF, \fBmsNone\fP = 0x00 }"
.br
.ti -1c
.RI "enum \fBAntialiasedElement\fP { \fBaeAxes\fP = 0x0001, \fBaeGrid\fP = 0x0002, \fBaeSubGrid\fP = 0x0004, \fBaeLegend\fP = 0x0008, \fBaeLegendItems\fP = 0x0010, \fBaePlottables\fP = 0x0020, \fBaeItems\fP = 0x0040, \fBaeScatters\fP = 0x0080, \fBaeFills\fP = 0x0100, \fBaeZeroLine\fP = 0x0200, \fBaeOther\fP = 0x8000, \fBaeAll\fP = 0xFFFF, \fBaeNone\fP = 0x0000 }"
.br
.ti -1c
.RI "enum \fBPlottingHint\fP { \fBphNone\fP = 0x000, \fBphFastPolylines\fP = 0x001, \fBphImmediateRefresh\fP = 0x002, \fBphCacheLabels\fP = 0x004 }"
.br
.ti -1c
.RI "enum \fBInteraction\fP { \fBiRangeDrag\fP = 0x001, \fBiRangeZoom\fP = 0x002, \fBiMultiSelect\fP = 0x004, \fBiSelectPlottables\fP = 0x008, \fBiSelectAxes\fP = 0x010, \fBiSelectLegend\fP = 0x020, \fBiSelectItems\fP = 0x040, \fBiSelectOther\fP = 0x080 }"
.br
.ti -1c
.RI "enum \fBSelectionRectMode\fP { \fBsrmNone\fP, \fBsrmZoom\fP, \fBsrmSelect\fP, \fBsrmCustom\fP }"
.br
.ti -1c
.RI "enum \fBSelectionType\fP { \fBstNone\fP, \fBstWhole\fP, \fBstSingleData\fP, \fBstDataRange\fP, \fBstMultipleDataRanges\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBisInvalidData\fP (double value)"
.br
.ti -1c
.RI "bool \fBisInvalidData\fP (double value1, double value2)"
.br
.ti -1c
.RI "void \fBsetMarginValue\fP (QMargins &margins, \fBQCP::MarginSide\fP side, int value)"
.br
.ti -1c
.RI "int \fBgetMarginValue\fP (const QMargins &margins, \fBQCP::MarginSide\fP side)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const QMetaObject \fBstaticMetaObject\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBQCP\fP Namespace contains general enums, QFlags and functions used throughout the \fBQCustomPlot\fP library\&.
.PP
It provides QMetaObject-based reflection of its enums and flags via \fIQCP::staticMetaObject\fP\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBQCP::AntialiasedElement\fP"
Defines what objects of a plot can be forcibly drawn antialiased/not antialiased\&. If an object is neither forcibly drawn antialiased nor forcibly drawn not antialiased, it is up to the respective element how it is drawn\&. Typically it provides a \fIsetAntialiased\fP function for this\&.
.PP
\fCAntialiasedElements\fP is a flag of or-combined elements of this enum type\&.
.PP
\fBSee also\fP
.RS 4
\fBQCustomPlot::setAntialiasedElements\fP, \fBQCustomPlot::setNotAntialiasedElements\fP 
.RE
.PP

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIaeAxes \fP\fP
\fC0x0001\fP Axis base line and tick marks 
.TP
\fB\fIaeGrid \fP\fP
\fC0x0002\fP Grid lines 
.TP
\fB\fIaeSubGrid \fP\fP
\fC0x0004\fP Sub grid lines 
.TP
\fB\fIaeLegend \fP\fP
\fC0x0008\fP Legend box 
.TP
\fB\fIaeLegendItems \fP\fP
\fC0x0010\fP Legend items 
.TP
\fB\fIaePlottables \fP\fP
\fC0x0020\fP Main lines of plottables 
.TP
\fB\fIaeItems \fP\fP
\fC0x0040\fP Main lines of items 
.TP
\fB\fIaeScatters \fP\fP
\fC0x0080\fP Scatter symbols of plottables (excluding scatter symbols of type ssPixmap) 
.TP
\fB\fIaeFills \fP\fP
\fC0x0100\fP Borders of fills (e\&.g\&. under or between graphs) 
.TP
\fB\fIaeZeroLine \fP\fP
\fC0x0200\fP Zero-lines, see \fBQCPGrid::setZeroLinePen\fP 
.TP
\fB\fIaeOther \fP\fP
\fC0x8000\fP Other elements that don't fit into any of the existing categories 
.TP
\fB\fIaeAll \fP\fP
\fC0xFFFF\fP All elements 
.TP
\fB\fIaeNone \fP\fP
\fC0x0000\fP No elements 
.PP
Definition at line \fB214\fP of file \fBqcustomplot\&.h\fP\&.
.SS "enum \fBQCP::ExportPen\fP"
Defines how cosmetic pens (pens with numerical width 0) are handled during export\&.
.PP
\fBSee also\fP
.RS 4
\fBQCustomPlot::savePdf\fP 
.RE
.PP

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIepNoCosmetic \fP\fP
Cosmetic pens are converted to pens with pixel width 1 when exporting\&. 
.TP
\fB\fIepAllowCosmetic \fP\fP
Cosmetic pens are exported normally (e\&.g\&. in PDF exports, cosmetic pens always appear as 1 pixel on screen, independent of viewer zoom level) 
.PP
Definition at line \fB175\fP of file \fBqcustomplot\&.h\fP\&.
.SS "enum \fBQCP::Interaction\fP"
Defines the mouse interactions possible with \fBQCustomPlot\fP\&.
.PP
\fCInteractions\fP is a flag of or-combined elements of this enum type\&.
.PP
\fBSee also\fP
.RS 4
\fBQCustomPlot::setInteractions\fP 
.RE
.PP

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIiRangeDrag \fP\fP
\fC0x001\fP Axis ranges are draggable (see \fBQCPAxisRect::setRangeDrag\fP, \fBQCPAxisRect::setRangeDragAxes\fP) 
.TP
\fB\fIiRangeZoom \fP\fP
\fC0x002\fP Axis ranges are zoomable with the mouse wheel (see \fBQCPAxisRect::setRangeZoom\fP, \fBQCPAxisRect::setRangeZoomAxes\fP) 
.TP
\fB\fIiMultiSelect \fP\fP
\fC0x004\fP The user can select multiple objects by holding the modifier set by \fBQCustomPlot::setMultiSelectModifier\fP while clicking 
.TP
\fB\fIiSelectPlottables \fP\fP
\fC0x008\fP Plottables are selectable (e\&.g\&. graphs, curves, bars,\&.\&.\&. see \fBQCPAbstractPlottable\fP) 
.TP
\fB\fIiSelectAxes \fP\fP
\fC0x010\fP Axes are selectable (or parts of them, see \fBQCPAxis::setSelectableParts\fP) 
.TP
\fB\fIiSelectLegend \fP\fP
\fC0x020\fP Legends are selectable (or their child items, see \fBQCPLegend::setSelectableParts\fP) 
.TP
\fB\fIiSelectItems \fP\fP
\fC0x040\fP Items are selectable (Rectangles, Arrows, Textitems, etc\&. see \fBQCPAbstractItem\fP) 
.TP
\fB\fIiSelectOther \fP\fP
\fC0x080\fP All other objects are selectable (e\&.g\&. your own derived layerables, other layout elements,\&.\&.\&.) 
.PP
Definition at line \fB251\fP of file \fBqcustomplot\&.h\fP\&.
.SS "enum \fBQCP::MarginSide\fP"
Defines the sides of a rectangular entity to which margins can be applied\&.
.PP
\fBSee also\fP
.RS 4
\fBQCPLayoutElement::setAutoMargins\fP, \fBQCPAxisRect::setAutoMargins\fP 
.RE
.PP

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fImsLeft \fP\fP
\fC0x01\fP left margin 
.TP
\fB\fImsRight \fP\fP
\fC0x02\fP right margin 
.TP
\fB\fImsTop \fP\fP
\fC0x04\fP top margin 
.TP
\fB\fImsBottom \fP\fP
\fC0x08\fP bottom margin 
.TP
\fB\fImsAll \fP\fP
\fC0xFF\fP all margins 
.TP
\fB\fImsNone \fP\fP
\fC0x00\fP no margin 
.PP
Definition at line \fB196\fP of file \fBqcustomplot\&.h\fP\&.
.SS "enum \fBQCP::PlottingHint\fP"
Defines plotting hints that control various aspects of the quality and speed of plotting\&.
.PP
\fBSee also\fP
.RS 4
\fBQCustomPlot::setPlottingHints\fP 
.RE
.PP

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIphNone \fP\fP
\fC0x000\fP No hints are set 
.TP
\fB\fIphFastPolylines \fP\fP
\fC0x001\fP Graph/Curve lines are drawn with a faster method\&. This reduces the quality especially of the line segment joins, thus is most effective for pen sizes larger than 1\&. It is only used for solid line pens\&. 
.TP
\fB\fIphImmediateRefresh \fP\fP
\fC0x002\fP causes an immediate repaint() instead of a soft update() when \fBQCustomPlot::replot()\fP is called with parameter \fBQCustomPlot::rpRefreshHint\fP\&. This is set by default to prevent the plot from freezing on fast consecutive replots (e\&.g\&. user drags ranges with mouse)\&. 
.TP
\fB\fIphCacheLabels \fP\fP
\fC0x004\fP axis (tick) labels will be cached as pixmaps, increasing replot performance\&. 
.PP
Definition at line \fB235\fP of file \fBqcustomplot\&.h\fP\&.
.SS "enum \fBQCP::ResolutionUnit\fP"
Defines the different units in which the image resolution can be specified in the export functions\&.
.PP
\fBSee also\fP
.RS 4
\fBQCustomPlot::savePng\fP, \fBQCustomPlot::saveJpg\fP, \fBQCustomPlot::saveBmp\fP, \fBQCustomPlot::saveRastered\fP 
.RE
.PP

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIruDotsPerMeter \fP\fP
Resolution is given in dots per meter (dpm) 
.TP
\fB\fIruDotsPerCentimeter \fP\fP
Resolution is given in dots per centimeter (dpcm) 
.TP
\fB\fIruDotsPerInch \fP\fP
Resolution is given in dots per inch (DPI/PPI) 
.PP
Definition at line \fB165\fP of file \fBqcustomplot\&.h\fP\&.
.SS "enum \fBQCP::SelectionRectMode\fP"
Defines the behaviour of the selection rect\&.
.PP
\fBSee also\fP
.RS 4
\fBQCustomPlot::setSelectionRectMode\fP, \fBQCustomPlot::selectionRect\fP, \fBQCPSelectionRect\fP 
.RE
.PP

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIsrmNone \fP\fP
The selection rect is disabled, and all mouse events are forwarded to the underlying objects, e\&.g\&. for axis range dragging\&. 
.TP
\fB\fIsrmZoom \fP\fP
When dragging the mouse, a selection rect becomes active\&. Upon releasing, the axes that are currently set as range zoom axes (\fBQCPAxisRect::setRangeZoomAxes\fP) will have their ranges zoomed accordingly\&. 
.TP
\fB\fIsrmSelect \fP\fP
When dragging the mouse, a selection rect becomes active\&. Upon releasing, plottable data points that were within the selection rect are selected, if the plottable's selectability setting permits\&. (See \fBdata selection mechanism\fP for details\&.) 
.TP
\fB\fIsrmCustom \fP\fP
When dragging the mouse, a selection rect becomes active\&. It is the programmer's responsibility to connect according slots to the selection rect's signals (e\&.g\&. \fBQCPSelectionRect::accepted\fP) in order to process the user interaction\&. 
.PP
Definition at line \fB267\fP of file \fBqcustomplot\&.h\fP\&.
.SS "enum \fBQCP::SelectionType\fP"
Defines the different ways a plottable can be selected\&. These images show the effect of the different selection types, when the indicated selection rect was dragged:
.PP
 td td td td td  
.PP
\fBSee also\fP
.RS 4
\fBQCPAbstractPlottable::setSelectable\fP, \fBQCPDataSelection::enforceType\fP 
.RE
.PP

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIstNone \fP\fP
The plottable is not selectable\&. 
.TP
\fB\fIstWhole \fP\fP
Selection behaves like \fBstMultipleDataRanges\fP, but if there are any data points selected, the entire plottable is drawn as selected\&. 
.TP
\fB\fIstSingleData \fP\fP
One individual data point can be selected at a time\&. 
.TP
\fB\fIstDataRange \fP\fP
Multiple contiguous data points (a data range) can be selected\&. 
.TP
\fB\fIstMultipleDataRanges \fP\fP
Any combination of data points/ranges can be selected\&. 
.PP
Definition at line \fB291\fP of file \fBqcustomplot\&.h\fP\&.
.SS "enum \fBQCP::SignDomain\fP"
Represents negative and positive sign domain, e\&.g\&. for passing to \fBQCPAbstractPlottable::getKeyRange\fP and \fBQCPAbstractPlottable::getValueRange\fP\&.
.PP
This is primarily needed when working with logarithmic axis scales, since only one of the sign domains can be visible at a time\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIsdNegative \fP\fP
The negative sign domain, i\&.e\&. numbers smaller than zero\&. 
.TP
\fB\fIsdBoth \fP\fP
Both sign domains, including zero, i\&.e\&. all numbers\&. 
.TP
\fB\fIsdPositive \fP\fP
The positive sign domain, i\&.e\&. numbers greater than zero\&. 
.PP
Definition at line \fB186\fP of file \fBqcustomplot\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "int QCP::getMarginValue (const QMargins & margins, \fBQCP::MarginSide\fP side)\fC [inline]\fP"

.PP
Definition at line \fB345\fP of file \fBqcustomplot\&.h\fP\&.
.SS "bool QCP::isInvalidData (double value)\fC [inline]\fP"

.PP
Definition at line \fB304\fP of file \fBqcustomplot\&.h\fP\&.
.SS "bool QCP::isInvalidData (double value1, double value2)\fC [inline]\fP"

.PP
Definition at line \fB314\fP of file \fBqcustomplot\&.h\fP\&.
.SS "void QCP::setMarginValue (QMargins & margins, \fBQCP::MarginSide\fP side, int value)\fC [inline]\fP"

.PP
Definition at line \fB325\fP of file \fBqcustomplot\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OmronPID from the source code\&.
