.TH "QCPAxisPainterPrivate::TickLabelData" 3 "Wed Mar 15 2023" "OmronPID" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QCPAxisPainterPrivate::TickLabelData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBbasePart\fP"
.br
.ti -1c
.RI "QString \fBexpPart\fP"
.br
.ti -1c
.RI "QString \fBsuffixPart\fP"
.br
.ti -1c
.RI "QRect \fBbaseBounds\fP"
.br
.ti -1c
.RI "QRect \fBexpBounds\fP"
.br
.ti -1c
.RI "QRect \fBsuffixBounds\fP"
.br
.ti -1c
.RI "QRect \fBtotalBounds\fP"
.br
.ti -1c
.RI "QRect \fBrotatedTotalBounds\fP"
.br
.ti -1c
.RI "QFont \fBbaseFont\fP"
.br
.ti -1c
.RI "QFont \fBexpFont\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB2262\fP of file \fBqcustomplot\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "QRect QCPAxisPainterPrivate::TickLabelData::baseBounds"

.PP
Definition at line \fB2265\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QFont QCPAxisPainterPrivate::TickLabelData::baseFont"

.PP
Definition at line \fB2266\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QString QCPAxisPainterPrivate::TickLabelData::basePart"

.PP
Definition at line \fB2264\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QRect QCPAxisPainterPrivate::TickLabelData::expBounds"

.PP
Definition at line \fB2265\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QFont QCPAxisPainterPrivate::TickLabelData::expFont"

.PP
Definition at line \fB2266\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QString QCPAxisPainterPrivate::TickLabelData::expPart"

.PP
Definition at line \fB2264\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QRect QCPAxisPainterPrivate::TickLabelData::rotatedTotalBounds"

.PP
Definition at line \fB2265\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QRect QCPAxisPainterPrivate::TickLabelData::suffixBounds"

.PP
Definition at line \fB2265\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QString QCPAxisPainterPrivate::TickLabelData::suffixPart"

.PP
Definition at line \fB2264\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QRect QCPAxisPainterPrivate::TickLabelData::totalBounds"

.PP
Definition at line \fB2265\fP of file \fBqcustomplot\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OmronPID from the source code\&.
