.TH "QCPAxisPainterPrivate::CachedLabel" 3 "Wed Mar 15 2023" "OmronPID" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QCPAxisPainterPrivate::CachedLabel
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QPointF \fBoffset\fP"
.br
.ti -1c
.RI "QPixmap \fBpixmap\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB2257\fP of file \fBqcustomplot\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "QPointF QCPAxisPainterPrivate::CachedLabel::offset"

.PP
Definition at line \fB2259\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QPixmap QCPAxisPainterPrivate::CachedLabel::pixmap"

.PP
Definition at line \fB2260\fP of file \fBqcustomplot\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OmronPID from the source code\&.
