.TH "QCPAbstractItem" 3 "Wed Mar 15 2023" "OmronPID" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QCPAbstractItem \- The abstract base class for all items in a plot\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBQCPLayerable\fP\&.
.PP
Inherited by \fBQCPItemBracket\fP, \fBQCPItemCurve\fP, \fBQCPItemEllipse\fP, \fBQCPItemLine\fP, \fBQCPItemPixmap\fP, \fBQCPItemRect\fP, \fBQCPItemStraightLine\fP, \fBQCPItemText\fP, and \fBQCPItemTracer\fP\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBselectionChanged\fP (bool selected)"
.br
.ti -1c
.RI "void \fBselectableChanged\fP (bool selectable)"
.br
.in -1c

Signals inherited from \fBQCPLayerable\fP
.in +1c
.ti -1c
.RI "void \fBlayerChanged\fP (\fBQCPLayer\fP *newLayer)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQCPAbstractItem\fP (\fBQCustomPlot\fP *parentPlot)"
.br
.ti -1c
.RI "bool \fBclipToAxisRect\fP () const"
.br
.ti -1c
.RI "\fBQCPAxisRect\fP * \fBclipAxisRect\fP () const"
.br
.ti -1c
.RI "bool \fBselectable\fP () const"
.br
.ti -1c
.RI "bool \fBselected\fP () const"
.br
.ti -1c
.RI "void \fBsetClipToAxisRect\fP (bool clip)"
.br
.ti -1c
.RI "void \fBsetClipAxisRect\fP (\fBQCPAxisRect\fP *rect)"
.br
.ti -1c
.RI "Q_SLOT void \fBsetSelectable\fP (bool selectable)"
.br
.ti -1c
.RI "Q_SLOT void \fBsetSelected\fP (bool selected)"
.br
.ti -1c
.RI "virtual double \fBselectTest\fP (const QPointF &pos, bool onlySelectable, QVariant *details=0) const Q_DECL_OVERRIDE=0"
.br
.ti -1c
.RI "QList< \fBQCPItemPosition\fP * > \fBpositions\fP () const"
.br
.ti -1c
.RI "QList< \fBQCPItemAnchor\fP * > \fBanchors\fP () const"
.br
.ti -1c
.RI "\fBQCPItemPosition\fP * \fBposition\fP (const QString &name) const"
.br
.ti -1c
.RI "\fBQCPItemAnchor\fP * \fBanchor\fP (const QString &name) const"
.br
.ti -1c
.RI "bool \fBhasAnchor\fP (const QString &name) const"
.br
.in -1c

Public Member Functions inherited from \fBQCPLayerable\fP
.in +1c
.ti -1c
.RI "\fBQCPLayerable\fP (\fBQCustomPlot\fP *plot, QString targetLayer=QString(), \fBQCPLayerable\fP *\fBparentLayerable\fP=0)"
.br
.ti -1c
.RI "bool \fBvisible\fP () const"
.br
.ti -1c
.RI "\fBQCustomPlot\fP * \fBparentPlot\fP () const"
.br
.ti -1c
.RI "\fBQCPLayerable\fP * \fBparentLayerable\fP () const"
.br
.ti -1c
.RI "\fBQCPLayer\fP * \fBlayer\fP () const"
.br
.ti -1c
.RI "bool \fBantialiased\fP () const"
.br
.ti -1c
.RI "void \fBsetVisible\fP (bool on)"
.br
.ti -1c
.RI "Q_SLOT bool \fBsetLayer\fP (\fBQCPLayer\fP *layer)"
.br
.ti -1c
.RI "bool \fBsetLayer\fP (const QString &layerName)"
.br
.ti -1c
.RI "void \fBsetAntialiased\fP (bool enabled)"
.br
.ti -1c
.RI "virtual double \fBselectTest\fP (const QPointF &pos, bool onlySelectable, QVariant *details=0) const"
.br
.ti -1c
.RI "bool \fBrealVisibility\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBQCP::Interaction\fP \fBselectionCategory\fP () const Q_DECL_OVERRIDE"
.br
.ti -1c
.RI "virtual QRect \fBclipRect\fP () const Q_DECL_OVERRIDE"
.br
.ti -1c
.RI "virtual void \fBapplyDefaultAntialiasingHint\fP (\fBQCPPainter\fP *painter) const Q_DECL_OVERRIDE"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (\fBQCPPainter\fP *painter) Q_DECL_OVERRIDE=0"
.br
.ti -1c
.RI "virtual void \fBselectEvent\fP (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged) Q_DECL_OVERRIDE"
.br
.ti -1c
.RI "virtual void \fBdeselectEvent\fP (bool *selectionStateChanged) Q_DECL_OVERRIDE"
.br
.ti -1c
.RI "virtual QPointF \fBanchorPixelPosition\fP (int anchorId) const"
.br
.ti -1c
.RI "double \fBrectDistance\fP (const QRectF &rect, const QPointF &pos, bool filledRect) const"
.br
.ti -1c
.RI "\fBQCPItemPosition\fP * \fBcreatePosition\fP (const QString &name)"
.br
.ti -1c
.RI "\fBQCPItemAnchor\fP * \fBcreateAnchor\fP (const QString &name, int anchorId)"
.br
.in -1c

Protected Member Functions inherited from \fBQCPLayerable\fP
.in +1c
.ti -1c
.RI "virtual void \fBparentPlotInitialized\fP (\fBQCustomPlot\fP *parentPlot)"
.br
.ti -1c
.RI "virtual \fBQCP::Interaction\fP \fBselectionCategory\fP () const"
.br
.ti -1c
.RI "virtual QRect \fBclipRect\fP () const"
.br
.ti -1c
.RI "virtual void \fBapplyDefaultAntialiasingHint\fP (\fBQCPPainter\fP *painter) const =0"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (\fBQCPPainter\fP *painter)=0"
.br
.ti -1c
.RI "virtual void \fBselectEvent\fP (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)"
.br
.ti -1c
.RI "virtual void \fBdeselectEvent\fP (bool *selectionStateChanged)"
.br
.ti -1c
.RI "virtual void \fBmousePressEvent\fP (QMouseEvent *event, const QVariant &details)"
.br
.ti -1c
.RI "virtual void \fBmouseMoveEvent\fP (QMouseEvent *event, const QPointF &startPos)"
.br
.ti -1c
.RI "virtual void \fBmouseReleaseEvent\fP (QMouseEvent *event, const QPointF &startPos)"
.br
.ti -1c
.RI "virtual void \fBmouseDoubleClickEvent\fP (QMouseEvent *event, const QVariant &details)"
.br
.ti -1c
.RI "virtual void \fBwheelEvent\fP (QWheelEvent *event)"
.br
.ti -1c
.RI "void \fBinitializeParentPlot\fP (\fBQCustomPlot\fP *parentPlot)"
.br
.ti -1c
.RI "void \fBsetParentLayerable\fP (\fBQCPLayerable\fP *\fBparentLayerable\fP)"
.br
.ti -1c
.RI "bool \fBmoveToLayer\fP (\fBQCPLayer\fP *layer, bool prepend)"
.br
.ti -1c
.RI "void \fBapplyAntialiasingHint\fP (\fBQCPPainter\fP *painter, bool localAntialiased, \fBQCP::AntialiasedElement\fP overrideElement) const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBmClipToAxisRect\fP"
.br
.ti -1c
.RI "QPointer< \fBQCPAxisRect\fP > \fBmClipAxisRect\fP"
.br
.ti -1c
.RI "QList< \fBQCPItemPosition\fP * > \fBmPositions\fP"
.br
.ti -1c
.RI "QList< \fBQCPItemAnchor\fP * > \fBmAnchors\fP"
.br
.ti -1c
.RI "bool \fBmSelectable\fP"
.br
.ti -1c
.RI "bool \fBmSelected\fP"
.br
.in -1c

Protected Attributes inherited from \fBQCPLayerable\fP
.in +1c
.ti -1c
.RI "bool \fBmVisible\fP"
.br
.ti -1c
.RI "\fBQCustomPlot\fP * \fBmParentPlot\fP"
.br
.ti -1c
.RI "QPointer< \fBQCPLayerable\fP > \fBmParentLayerable\fP"
.br
.ti -1c
.RI "\fBQCPLayer\fP * \fBmLayer\fP"
.br
.ti -1c
.RI "bool \fBmAntialiased\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBQCustomPlot\fP"
.br
.ti -1c
.RI "class \fBQCPItemAnchor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The abstract base class for all items in a plot\&. 

In \fBQCustomPlot\fP, items are supplemental graphical elements that are neither plottables (\fBQCPAbstractPlottable\fP) nor axes (\fBQCPAxis\fP)\&. While plottables are always tied to two axes and thus plot coordinates, items can also be placed in absolute coordinates independent of any axes\&. Each specific item has at least one \fBQCPItemPosition\fP member which controls the positioning\&. Some items are defined by more than one coordinate and thus have two or more \fBQCPItemPosition\fP members (For example, \fBQCPItemRect\fP has \fItopLeft\fP and \fIbottomRight\fP)\&.
.PP
This abstract base class defines a very basic interface like visibility and clipping\&. Since this class is abstract, it can't be instantiated\&. Use one of the subclasses or create a subclass yourself to create new items\&.
.PP
The built-in items are: \fBQCPItemLine\fPA line defined by a start and an end point\&. May have different ending styles on each side (e\&.g\&. arrows)\&. \fBQCPItemStraightLine\fPA straight line defined by a start and a direction point\&. Unlike \fBQCPItemLine\fP, the straight line is infinitely long and has no endings\&. \fBQCPItemCurve\fPA curve defined by start, end and two intermediate control points\&. May have different ending styles on each side (e\&.g\&. arrows)\&. \fBQCPItemRect\fPA rectangle \fBQCPItemEllipse\fPAn ellipse \fBQCPItemPixmap\fPAn arbitrary pixmap \fBQCPItemText\fPA text label \fBQCPItemBracket\fPA bracket which may be used to reference/highlight certain parts in the plot\&. \fBQCPItemTracer\fPAn item that can be attached to a \fBQCPGraph\fP and sticks to its data points, given a key coordinate\&. 
.SH "Clipping"
.PP
Items are by default clipped to the main axis rect (they are only visible inside the axis rect)\&. To make an item visible outside that axis rect, disable clipping via \fBsetClipToAxisRect(false)\fP\&.
.PP
On the other hand if you want the item to be clipped to a different axis rect, specify it via \fBsetClipAxisRect\fP\&. This clipAxisRect property of an item is only used for clipping behaviour, and in principle is independent of the coordinate axes the item might be tied to via its position members (\fBQCPItemPosition::setAxes\fP)\&. However, it is common that the axis rect for clipping also contains the axes used for the item positions\&.
.SH "Using items"
.PP
First you instantiate the item you want to use and add it to the plot: 
.PP
.nf

.fi
.PP
 by default, the positions of the item are bound to the x- and y-Axis of the plot\&. So we can just set the plot coordinates where the line should start/end: 
.PP
.nf

.fi
.PP
 If we don't want the line to be positioned in plot coordinates but a different coordinate system, e\&.g\&. absolute pixel positions on the \fBQCustomPlot\fP surface, we need to change the position type like this: 
.PP
.nf

.fi
.PP
 Then we can set the coordinates, this time in pixels: 
.PP
.nf

.fi
.PP
 and make the line visible on the entire \fBQCustomPlot\fP, by disabling clipping to the axis rect: 
.PP
.nf

.fi
.PP
.PP
For more advanced plots, it is even possible to set different types and parent anchors per X/Y coordinate of an item position, using for example \fBQCPItemPosition::setTypeX\fP or \fBQCPItemPosition::setParentAnchorX\fP\&. For details, see the documentation of \fBQCPItemPosition\fP\&.
.SH "Creating own items"
.PP
To create an own item, you implement a subclass of \fBQCPAbstractItem\fP\&. These are the pure virtual functions, you must implement: 
.PD 0

.IP "\(bu" 2
\fBselectTest\fP 
.IP "\(bu" 2
\fBdraw\fP
.PP
See the documentation of those functions for what they need to do\&.
.SS "Allowing the item to be positioned"
As mentioned, item positions are represented by \fBQCPItemPosition\fP members\&. Let's assume the new item shall have only one point as its position (as opposed to two like a rect or multiple like a polygon)\&. You then add a public member of type \fBQCPItemPosition\fP like so:
.PP
.PP
.nf
QCPItemPosition * const myPosition;
.fi
.PP
.PP
the const makes sure the pointer itself can't be modified from the user of your new item (the \fBQCPItemPosition\fP instance it points to, can be modified, of course)\&. The initialization of this pointer is made easy with the \fBcreatePosition\fP function\&. Just assign the return value of this function to each \fBQCPItemPosition\fP in the constructor of your item\&. \fBcreatePosition\fP takes a string which is the name of the position, typically this is identical to the variable name\&. For example, the constructor of QCPItemExample could look like this:
.PP
.PP
.nf
QCPItemExample::QCPItemExample(QCustomPlot *parentPlot) :
  QCPAbstractItem(parentPlot),
  myPosition(createPosition("myPosition"))
{
  // other constructor code
}
.fi
.PP
.SS "The draw function"
To give your item a visual representation, reimplement the \fBdraw\fP function and use the passed \fBQCPPainter\fP to draw the item\&. You can retrieve the item position in pixel coordinates from the position member(s) via \fBQCPItemPosition::pixelPosition\fP\&.
.PP
To optimize performance you should calculate a bounding rect first (don't forget to take the pen width into account), check whether it intersects the \fBclipRect\fP, and only draw the item at all if this is the case\&.
.SS "The selectTest function"
Your implementation of the \fBselectTest\fP function may use the helpers \fBQCPVector2D::distanceSquaredToLine\fP and \fBrectDistance\fP\&. With these, the implementation of the selection test becomes significantly simpler for most items\&. See the documentation of \fBselectTest\fP for what the function parameters mean and what the function should return\&.
.SS "Providing anchors"
Providing anchors (\fBQCPItemAnchor\fP) starts off like adding a position\&. First you create a public member, e\&.g\&.
.PP
.PP
.nf
QCPItemAnchor * const bottom;
.fi
.PP
.PP
and create it in the constructor with the \fBcreateAnchor\fP function, assigning it a name and an anchor id (an integer enumerating all anchors on the item, you may create an own enum for this)\&. Since anchors can be placed anywhere, relative to the item's position(s), your item needs to provide the position of every anchor with the reimplementation of the \fBanchorPixelPosition(int
anchorId)\fP function\&.
.PP
In essence the \fBQCPItemAnchor\fP is merely an intermediary that itself asks your item for the pixel position when anything attached to the anchor needs to know the coordinates\&. 
.PP
Definition at line \fB3505\fP of file \fBqcustomplot\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QCPAbstractItem::QCPAbstractItem (\fBQCustomPlot\fP * parentPlot)\fC [explicit]\fP"
Base class constructor which initializes base class members\&. 
.PP
Definition at line \fB12203\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "QCPAbstractItem::~QCPAbstractItem ()\fC [virtual]\fP"

.PP
Definition at line \fB12219\fP of file \fBqcustomplot\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBQCPItemAnchor\fP * QCPAbstractItem::anchor (const QString & name) const"
Returns the \fBQCPItemAnchor\fP with the specified \fIname\fP\&. If this item doesn't have an anchor by that name, returns 0\&.
.PP
This function provides an alternative way to access item anchors\&. Normally, you access anchors direcly by their member pointers (which typically have the same variable name as \fIname\fP)\&.
.PP
\fBSee also\fP
.RS 4
\fBanchors\fP, \fBposition\fP 
.RE
.PP

.PP
Definition at line \fB12329\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "QPointF QCPAbstractItem::anchorPixelPosition (int anchorId) const\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB12442\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "QList< \fBQCPItemAnchor\fP * > QCPAbstractItem::anchors () const\fC [inline]\fP"
Returns all anchors of the item in a list\&. Note that since a position (\fBQCPItemPosition\fP) is always also an anchor, the list will also contain the positions of this item\&.
.PP
\fBSee also\fP
.RS 4
\fBpositions\fP, \fBanchor\fP 
.RE
.PP

.PP
Definition at line \fB3535\fP of file \fBqcustomplot\&.h\fP\&.
.SS "void QCPAbstractItem::applyDefaultAntialiasingHint (\fBQCPPainter\fP * painter) const\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBQCPLayerable\fP\&.
.PP
Definition at line \fB12388\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "\fBQCPAxisRect\fP * QCPAbstractItem::clipAxisRect () const"

.PP
Definition at line \fB12226\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "QRect QCPAbstractItem::clipRect () const\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBQCPLayerable\fP\&.
.PP
Definition at line \fB12367\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "bool QCPAbstractItem::clipToAxisRect () const\fC [inline]\fP"

.PP
Definition at line \fB3519\fP of file \fBqcustomplot\&.h\fP\&.
.SS "\fBQCPItemAnchor\fP * QCPAbstractItem::createAnchor (const QString & name, int anchorId)\fC [protected]\fP"

.PP
Definition at line \fB12496\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "\fBQCPItemPosition\fP * QCPAbstractItem::createPosition (const QString & name)\fC [protected]\fP"

.PP
Definition at line \fB12462\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPAbstractItem::deselectEvent (bool * selectionStateChanged)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBQCPLayerable\fP\&.
.PP
Definition at line \fB12520\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPAbstractItem::draw (\fBQCPPainter\fP * painter)\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implements \fBQCPLayerable\fP\&.
.SS "bool QCPAbstractItem::hasAnchor (const QString & name) const"
Returns whether this item has an anchor with the specified \fIname\fP\&.
.PP
Note that you can check for positions with this function, too\&. This is because every position is also an anchor (\fBQCPItemPosition\fP inherits from \fBQCPItemAnchor\fP)\&.
.PP
\fBSee also\fP
.RS 4
\fBanchor\fP, \fBposition\fP 
.RE
.PP

.PP
Definition at line \fB12348\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "\fBQCPItemPosition\fP * QCPAbstractItem::position (const QString & name) const"
Returns the \fBQCPItemPosition\fP with the specified \fIname\fP\&. If this item doesn't have a position by that name, returns 0\&.
.PP
This function provides an alternative way to access item positions\&. Normally, you access positions direcly by their member pointers (which typically have the same variable name as \fIname\fP)\&.
.PP
\fBSee also\fP
.RS 4
\fBpositions\fP, \fBanchor\fP 
.RE
.PP

.PP
Definition at line \fB12308\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "QList< \fBQCPItemPosition\fP * > QCPAbstractItem::positions () const\fC [inline]\fP"
Returns all positions of the item in a list\&.
.PP
\fBSee also\fP
.RS 4
\fBanchors\fP, \fBposition\fP 
.RE
.PP

.PP
Definition at line \fB3534\fP of file \fBqcustomplot\&.h\fP\&.
.SS "double QCPAbstractItem::rectDistance (const QRectF & rect, const QPointF & pos, bool filledRect) const\fC [protected]\fP"

.PP
Definition at line \fB12406\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "bool QCPAbstractItem::selectable () const\fC [inline]\fP"

.PP
Definition at line \fB3521\fP of file \fBqcustomplot\&.h\fP\&.
.SS "bool QCPAbstractItem::selected () const\fC [inline]\fP"

.PP
Definition at line \fB3522\fP of file \fBqcustomplot\&.h\fP\&.
.SS "void QCPAbstractItem::selectEvent (QMouseEvent * event, bool additive, const QVariant & details, bool * selectionStateChanged)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBQCPLayerable\fP\&.
.PP
Definition at line \fB12506\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "\fBQCP::Interaction\fP QCPAbstractItem::selectionCategory () const\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBQCPLayerable\fP\&.
.PP
Definition at line \fB12532\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPAbstractItem::selectionChanged (bool selected)\fC [signal]\fP"
This signal is emitted when the selection state of this item has changed, either by user interaction or by a direct call to \fBsetSelected\fP\&. 
.SS "virtual double QCPAbstractItem::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = \fC0\fP) const\fC [pure virtual]\fP"
This function is used to decide whether a click hits a layerable object or not\&.
.PP
\fIpos\fP is a point in pixel coordinates on the \fBQCustomPlot\fP surface\&. This function returns the shortest pixel distance of this point to the object\&. If the object is either invisible or the distance couldn't be determined, -1\&.0 is returned\&. Further, if \fIonlySelectable\fP is true and the object is not selectable, -1\&.0 is returned, too\&.
.PP
If the object is represented not by single lines but by an area like a \fBQCPItemText\fP or the bars of a \fBQCPBars\fP plottable, a click inside the area should also be considered a hit\&. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance\&. (typically the selectionTolerance multiplied by 0\&.99)\&.
.PP
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i\&.e\&. closer than 0\&.99*selectionTolerance)\&.
.PP
The actual setting of the selection state is not done by this function\&. This is handled by the parent \fBQCustomPlot\fP when the mouseReleaseEvent occurs, and the finally selected object is notified via the \fBselectEvent/\fP deselectEvent methods\&.
.PP
\fIdetails\fP is an optional output parameter\&. Every layerable subclass may place any information in \fIdetails\fP\&. This information will be passed to \fBselectEvent\fP when the parent \fBQCustomPlot\fP decides on the basis of this selectTest call, that the object was successfully selected\&. The subsequent call to \fBselectEvent\fP will carry the \fIdetails\fP\&. This is useful for multi-part objects (like \fBQCPAxis\fP)\&. This way, a possibly complex calculation to decide which part was clicked is only done once in \fBselectTest\fP\&. The result (i\&.e\&. the actually clicked part) can then be placed in \fIdetails\fP\&. So in the subsequent \fBselectEvent\fP, the decision which part was selected doesn't have to be done a second time for a single selection operation\&.
.PP
You may pass 0 as \fIdetails\fP to indicate that you are not interested in those selection details\&.
.PP
\fBSee also\fP
.RS 4
selectEvent, deselectEvent, \fBmousePressEvent\fP, \fBwheelEvent\fP, \fBQCustomPlot::setInteractions\fP 
.RE
.PP

.PP
Reimplemented from \fBQCPLayerable\fP\&.
.PP
Implemented in \fBQCPItemStraightLine\fP, \fBQCPItemLine\fP, \fBQCPItemCurve\fP, \fBQCPItemRect\fP, \fBQCPItemText\fP, \fBQCPItemEllipse\fP, \fBQCPItemPixmap\fP, \fBQCPItemTracer\fP, and \fBQCPItemBracket\fP\&.
.SS "void QCPAbstractItem::setClipAxisRect (\fBQCPAxisRect\fP * rect)"
Sets the clip axis rect\&. It defines the rect that will be used to clip the item when \fBsetClipToAxisRect\fP is set to true\&.
.PP
\fBSee also\fP
.RS 4
\fBsetClipToAxisRect\fP 
.RE
.PP

.PP
Definition at line \fB12250\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPAbstractItem::setClipToAxisRect (bool clip)"
Sets whether the item shall be clipped to an axis rect or whether it shall be visible on the entire \fBQCustomPlot\fP\&. The axis rect can be set with \fBsetClipAxisRect\fP\&.
.PP
\fBSee also\fP
.RS 4
\fBsetClipAxisRect\fP 
.RE
.PP

.PP
Definition at line \fB12237\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPAbstractItem::setSelectable (bool selectable)"
Sets whether the user can (de-)select this item by clicking on the \fBQCustomPlot\fP surface\&. (When \fBQCustomPlot::setInteractions\fP contains QCustomPlot::iSelectItems\&.)
.PP
However, even when \fIselectable\fP was set to false, it is possible to set the selection manually, by calling \fBsetSelected\fP\&.
.PP
\fBSee also\fP
.RS 4
\fBQCustomPlot::setInteractions\fP, \fBsetSelected\fP 
.RE
.PP

.PP
Definition at line \fB12266\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPAbstractItem::setSelected (bool selected)"
Sets whether this item is selected or not\&. When selected, it might use a different visual appearance (e\&.g\&. pen and brush), this depends on the specific item though\&.
.PP
The entire selection mechanism for items is handled automatically when \fBQCustomPlot::setInteractions\fP contains QCustomPlot::iSelectItems\&. You only need to call this function when you wish to change the selection state manually\&.
.PP
This function can change the selection state even when \fBsetSelectable\fP was set to false\&.
.PP
emits the \fBselectionChanged\fP signal when \fIselected\fP is different from the previous selection state\&.
.PP
\fBSee also\fP
.RS 4
\fBsetSelectable\fP, \fBselectTest\fP 
.RE
.PP

.PP
Definition at line \fB12289\fP of file \fBqcustomplot\&.cpp\fP\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBQCPItemAnchor\fP\fC [friend]\fP"

.PP
Definition at line \fB3573\fP of file \fBqcustomplot\&.h\fP\&.
.SS "friend class \fBQCustomPlot\fP\fC [friend]\fP"

.PP
Definition at line \fB3572\fP of file \fBqcustomplot\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "QList<\fBQCPItemAnchor\fP*> QCPAbstractItem::mAnchors\fC [protected]\fP"

.PP
Definition at line \fB3549\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QPointer<\fBQCPAxisRect\fP> QCPAbstractItem::mClipAxisRect\fC [protected]\fP"

.PP
Definition at line \fB3547\fP of file \fBqcustomplot\&.h\fP\&.
.SS "bool QCPAbstractItem::mClipToAxisRect\fC [protected]\fP"

.PP
Definition at line \fB3546\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QList<\fBQCPItemPosition\fP*> QCPAbstractItem::mPositions\fC [protected]\fP"

.PP
Definition at line \fB3548\fP of file \fBqcustomplot\&.h\fP\&.
.SS "bool QCPAbstractItem::mSelectable\fC [protected]\fP"

.PP
Definition at line \fB3550\fP of file \fBqcustomplot\&.h\fP\&.
.SS "bool QCPAbstractItem::mSelected\fC [protected]\fP"

.PP
Definition at line \fB3550\fP of file \fBqcustomplot\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OmronPID from the source code\&.
