.TH "QCPAxisPainterPrivate" 3 "Wed Mar 15 2023" "OmronPID" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QCPAxisPainterPrivate
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCachedLabel\fP"
.br
.ti -1c
.RI "struct \fBTickLabelData\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQCPAxisPainterPrivate\fP (\fBQCustomPlot\fP *parentPlot)"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (\fBQCPPainter\fP *painter)"
.br
.ti -1c
.RI "virtual int \fBsize\fP () const"
.br
.ti -1c
.RI "void \fBclearCache\fP ()"
.br
.ti -1c
.RI "QRect \fBaxisSelectionBox\fP () const"
.br
.ti -1c
.RI "QRect \fBtickLabelsSelectionBox\fP () const"
.br
.ti -1c
.RI "QRect \fBlabelSelectionBox\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBQCPAxis::AxisType\fP \fBtype\fP"
.br
.ti -1c
.RI "QPen \fBbasePen\fP"
.br
.ti -1c
.RI "\fBQCPLineEnding\fP \fBlowerEnding\fP"
.br
.ti -1c
.RI "\fBQCPLineEnding\fP \fBupperEnding\fP"
.br
.ti -1c
.RI "int \fBlabelPadding\fP"
.br
.ti -1c
.RI "QFont \fBlabelFont\fP"
.br
.ti -1c
.RI "QColor \fBlabelColor\fP"
.br
.ti -1c
.RI "QString \fBlabel\fP"
.br
.ti -1c
.RI "int \fBtickLabelPadding\fP"
.br
.ti -1c
.RI "double \fBtickLabelRotation\fP"
.br
.ti -1c
.RI "\fBQCPAxis::LabelSide\fP \fBtickLabelSide\fP"
.br
.ti -1c
.RI "bool \fBsubstituteExponent\fP"
.br
.ti -1c
.RI "bool \fBnumberMultiplyCross\fP"
.br
.ti -1c
.RI "int \fBtickLengthIn\fP"
.br
.ti -1c
.RI "int \fBtickLengthOut\fP"
.br
.ti -1c
.RI "int \fBsubTickLengthIn\fP"
.br
.ti -1c
.RI "int \fBsubTickLengthOut\fP"
.br
.ti -1c
.RI "QPen \fBtickPen\fP"
.br
.ti -1c
.RI "QPen \fBsubTickPen\fP"
.br
.ti -1c
.RI "QFont \fBtickLabelFont\fP"
.br
.ti -1c
.RI "QColor \fBtickLabelColor\fP"
.br
.ti -1c
.RI "QRect \fBaxisRect\fP"
.br
.ti -1c
.RI "QRect \fBviewportRect\fP"
.br
.ti -1c
.RI "double \fBoffset\fP"
.br
.ti -1c
.RI "bool \fBabbreviateDecimalPowers\fP"
.br
.ti -1c
.RI "bool \fBreversedEndings\fP"
.br
.ti -1c
.RI "QVector< double > \fBsubTickPositions\fP"
.br
.ti -1c
.RI "QVector< double > \fBtickPositions\fP"
.br
.ti -1c
.RI "QVector< QString > \fBtickLabels\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual QByteArray \fBgenerateLabelParameterHash\fP () const"
.br
.ti -1c
.RI "virtual void \fBplaceTickLabel\fP (\fBQCPPainter\fP *painter, double position, int distanceToAxis, const QString &text, QSize *tickLabelsSize)"
.br
.ti -1c
.RI "virtual void \fBdrawTickLabel\fP (\fBQCPPainter\fP *painter, double x, double y, const \fBTickLabelData\fP &labelData) const"
.br
.ti -1c
.RI "virtual \fBTickLabelData\fP \fBgetTickLabelData\fP (const QFont &font, const QString &text) const"
.br
.ti -1c
.RI "virtual QPointF \fBgetTickLabelDrawOffset\fP (const \fBTickLabelData\fP &labelData) const"
.br
.ti -1c
.RI "virtual void \fBgetMaxTickLabelSize\fP (const QFont &font, const QString &text, QSize *tickLabelsSize) const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBQCustomPlot\fP * \fBmParentPlot\fP"
.br
.ti -1c
.RI "QByteArray \fBmLabelParameterHash\fP"
.br
.ti -1c
.RI "QCache< QString, \fBCachedLabel\fP > \fBmLabelCache\fP"
.br
.ti -1c
.RI "QRect \fBmAxisSelectionBox\fP"
.br
.ti -1c
.RI "QRect \fBmTickLabelsSelectionBox\fP"
.br
.ti -1c
.RI "QRect \fBmLabelSelectionBox\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB2216\fP of file \fBqcustomplot\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QCPAxisPainterPrivate::QCPAxisPainterPrivate (\fBQCustomPlot\fP * parentPlot)\fC [explicit]\fP"
Constructs a \fBQCPAxisPainterPrivate\fP instance\&. Make sure to not create a new instance on every redraw, to utilize the caching mechanisms\&. 
.PP
Definition at line \fB9176\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "QCPAxisPainterPrivate::~QCPAxisPainterPrivate ()\fC [virtual]\fP"

.PP
Definition at line \fB9201\fP of file \fBqcustomplot\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "QRect QCPAxisPainterPrivate::axisSelectionBox () const\fC [inline]\fP"

.PP
Definition at line \fB2226\fP of file \fBqcustomplot\&.h\fP\&.
.SS "void QCPAxisPainterPrivate::clearCache ()"

.PP
Definition at line \fB9444\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPAxisPainterPrivate::draw (\fBQCPPainter\fP * painter)\fC [virtual]\fP"

.PP
Definition at line \fB9212\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPAxisPainterPrivate::drawTickLabel (\fBQCPPainter\fP * painter, double x, double y, const \fBTickLabelData\fP & labelData) const\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB9577\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "QByteArray QCPAxisPainterPrivate::generateLabelParameterHash () const\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB9456\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPAxisPainterPrivate::getMaxTickLabelSize (const QFont & font, const QString & text, QSize * tickLabelsSize) const\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB9798\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "\fBQCPAxisPainterPrivate::TickLabelData\fP QCPAxisPainterPrivate::getTickLabelData (const QFont & font, const QString & text) const\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB9616\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "QPointF QCPAxisPainterPrivate::getTickLabelDrawOffset (const \fBTickLabelData\fP & labelData) const\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB9698\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "QRect QCPAxisPainterPrivate::labelSelectionBox () const\fC [inline]\fP"

.PP
Definition at line \fB2228\fP of file \fBqcustomplot\&.h\fP\&.
.SS "void QCPAxisPainterPrivate::placeTickLabel (\fBQCPPainter\fP * painter, double position, int distanceToAxis, const QString & text, QSize * tickLabelsSize)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB9488\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "int QCPAxisPainterPrivate::size () const\fC [virtual]\fP"

.PP
Definition at line \fB9405\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "QRect QCPAxisPainterPrivate::tickLabelsSelectionBox () const\fC [inline]\fP"

.PP
Definition at line \fB2227\fP of file \fBqcustomplot\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool QCPAxisPainterPrivate::abbreviateDecimalPowers"

.PP
Definition at line \fB2249\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QRect QCPAxisPainterPrivate::axisRect"

.PP
Definition at line \fB2247\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QPen QCPAxisPainterPrivate::basePen"

.PP
Definition at line \fB2232\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QString QCPAxisPainterPrivate::label"

.PP
Definition at line \fB2237\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QColor QCPAxisPainterPrivate::labelColor"

.PP
Definition at line \fB2236\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QFont QCPAxisPainterPrivate::labelFont"

.PP
Definition at line \fB2235\fP of file \fBqcustomplot\&.h\fP\&.
.SS "int QCPAxisPainterPrivate::labelPadding"

.PP
Definition at line \fB2234\fP of file \fBqcustomplot\&.h\fP\&.
.SS "\fBQCPLineEnding\fP QCPAxisPainterPrivate::lowerEnding"

.PP
Definition at line \fB2233\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QRect QCPAxisPainterPrivate::mAxisSelectionBox\fC [protected]\fP"

.PP
Definition at line \fB2271\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QCache<QString, \fBCachedLabel\fP> QCPAxisPainterPrivate::mLabelCache\fC [protected]\fP"

.PP
Definition at line \fB2270\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QByteArray QCPAxisPainterPrivate::mLabelParameterHash\fC [protected]\fP"

.PP
Definition at line \fB2269\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QRect QCPAxisPainterPrivate::mLabelSelectionBox\fC [protected]\fP"

.PP
Definition at line \fB2271\fP of file \fBqcustomplot\&.h\fP\&.
.SS "\fBQCustomPlot\fP* QCPAxisPainterPrivate::mParentPlot\fC [protected]\fP"

.PP
Definition at line \fB2268\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QRect QCPAxisPainterPrivate::mTickLabelsSelectionBox\fC [protected]\fP"

.PP
Definition at line \fB2271\fP of file \fBqcustomplot\&.h\fP\&.
.SS "bool QCPAxisPainterPrivate::numberMultiplyCross"

.PP
Definition at line \fB2242\fP of file \fBqcustomplot\&.h\fP\&.
.SS "double QCPAxisPainterPrivate::offset"

.PP
Definition at line \fB2248\fP of file \fBqcustomplot\&.h\fP\&.
.SS "bool QCPAxisPainterPrivate::reversedEndings"

.PP
Definition at line \fB2250\fP of file \fBqcustomplot\&.h\fP\&.
.SS "bool QCPAxisPainterPrivate::substituteExponent"

.PP
Definition at line \fB2241\fP of file \fBqcustomplot\&.h\fP\&.
.SS "int QCPAxisPainterPrivate::subTickLengthIn"

.PP
Definition at line \fB2243\fP of file \fBqcustomplot\&.h\fP\&.
.SS "int QCPAxisPainterPrivate::subTickLengthOut"

.PP
Definition at line \fB2243\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QPen QCPAxisPainterPrivate::subTickPen"

.PP
Definition at line \fB2244\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QVector<double> QCPAxisPainterPrivate::subTickPositions"

.PP
Definition at line \fB2252\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QColor QCPAxisPainterPrivate::tickLabelColor"

.PP
Definition at line \fB2246\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QFont QCPAxisPainterPrivate::tickLabelFont"

.PP
Definition at line \fB2245\fP of file \fBqcustomplot\&.h\fP\&.
.SS "int QCPAxisPainterPrivate::tickLabelPadding"

.PP
Definition at line \fB2238\fP of file \fBqcustomplot\&.h\fP\&.
.SS "double QCPAxisPainterPrivate::tickLabelRotation"

.PP
Definition at line \fB2239\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QVector<QString> QCPAxisPainterPrivate::tickLabels"

.PP
Definition at line \fB2254\fP of file \fBqcustomplot\&.h\fP\&.
.SS "\fBQCPAxis::LabelSide\fP QCPAxisPainterPrivate::tickLabelSide"

.PP
Definition at line \fB2240\fP of file \fBqcustomplot\&.h\fP\&.
.SS "int QCPAxisPainterPrivate::tickLengthIn"

.PP
Definition at line \fB2243\fP of file \fBqcustomplot\&.h\fP\&.
.SS "int QCPAxisPainterPrivate::tickLengthOut"

.PP
Definition at line \fB2243\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QPen QCPAxisPainterPrivate::tickPen"

.PP
Definition at line \fB2244\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QVector<double> QCPAxisPainterPrivate::tickPositions"

.PP
Definition at line \fB2253\fP of file \fBqcustomplot\&.h\fP\&.
.SS "\fBQCPAxis::AxisType\fP QCPAxisPainterPrivate::type"

.PP
Definition at line \fB2231\fP of file \fBqcustomplot\&.h\fP\&.
.SS "\fBQCPLineEnding\fP QCPAxisPainterPrivate::upperEnding"

.PP
Definition at line \fB2233\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QRect QCPAxisPainterPrivate::viewportRect"

.PP
Definition at line \fB2247\fP of file \fBqcustomplot\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OmronPID from the source code\&.
