.TH "QCPCurveData" 3 "Wed Mar 15 2023" "OmronPID" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QCPCurveData \- Holds the data of one single data point for \fBQCPCurve\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQCPCurveData\fP ()"
.br
.ti -1c
.RI "\fBQCPCurveData\fP (double t, double key, double value)"
.br
.ti -1c
.RI "double \fBsortKey\fP () const"
.br
.ti -1c
.RI "double \fBmainKey\fP () const"
.br
.ti -1c
.RI "double \fBmainValue\fP () const"
.br
.ti -1c
.RI "\fBQCPRange\fP \fBvalueRange\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBQCPCurveData\fP \fBfromSortKey\fP (double \fBsortKey\fP)"
.br
.ti -1c
.RI "static bool \fBsortKeyIsMainKey\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBt\fP"
.br
.ti -1c
.RI "double \fBkey\fP"
.br
.ti -1c
.RI "double \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds the data of one single data point for \fBQCPCurve\fP\&. 

The stored data is: 
.PD 0

.IP "\(bu" 2
\fIt:\fP the free ordering parameter of this curve point, like in the mathematical vector \fI(x(t), y(t))\fP\&. (This is the \fIsortKey\fP) 
.IP "\(bu" 2
\fIkey:\fP coordinate on the key axis of this curve point (this is the \fImainKey\fP) 
.IP "\(bu" 2
\fIvalue:\fP coordinate on the value axis of this curve point (this is the \fImainValue\fP)
.PP
The container for storing multiple data points is \fBQCPCurveDataContainer\fP\&. It is a typedef for \fBQCPDataContainer\fP with \fBQCPCurveData\fP as the DataType template parameter\&. See the documentation there for an explanation regarding the data type's generic methods\&.
.PP
\fBSee also\fP
.RS 4
QCPCurveDataContainer 
.RE
.PP

.PP
Definition at line \fB5260\fP of file \fBqcustomplot\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QCPCurveData::QCPCurveData ()"
Constructs a curve data point with t, key and value set to zero\&. 
.PP
Definition at line \fB21729\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "QCPCurveData::QCPCurveData (double t, double key, double value)"
Constructs a curve data point with the specified \fIt\fP, \fIkey\fP and \fIvalue\fP\&. 
.PP
Definition at line \fB21739\fP of file \fBqcustomplot\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBQCPCurveData\fP QCPCurveData::fromSortKey (double sortKey)\fC [inline]\fP, \fC [static]\fP"
Returns a data point with the specified \fIsortKey\fP (assigned to the data point's \fIt\fP member)\&. All other members are set to zero\&.
.PP
For a general explanation of what this method is good for in the context of the data container, see the documentation of \fBQCPDataContainer\fP\&. 
.PP
Definition at line \fB5267\fP of file \fBqcustomplot\&.h\fP\&.
.SS "double QCPCurveData::mainKey () const\fC [inline]\fP"
Returns the \fIkey\fP member of this data point\&.
.PP
For a general explanation of what this method is good for in the context of the data container, see the documentation of \fBQCPDataContainer\fP\&. 
.PP
Definition at line \fB5270\fP of file \fBqcustomplot\&.h\fP\&.
.SS "double QCPCurveData::mainValue () const\fC [inline]\fP"
Returns the \fIvalue\fP member of this data point\&.
.PP
For a general explanation of what this method is good for in the context of the data container, see the documentation of \fBQCPDataContainer\fP\&. 
.PP
Definition at line \fB5271\fP of file \fBqcustomplot\&.h\fP\&.
.SS "double QCPCurveData::sortKey () const\fC [inline]\fP"
Returns the \fIt\fP member of this data point\&.
.PP
For a general explanation of what this method is good for in the context of the data container, see the documentation of \fBQCPDataContainer\fP\&. 
.PP
Definition at line \fB5266\fP of file \fBqcustomplot\&.h\fP\&.
.SS "static static bool QCPCurveData::sortKeyIsMainKey ()\fC [inline]\fP, \fC [static]\fP"
Since the member \fIkey\fP is the data point key coordinate and the member \fIt\fP is the data ordering parameter, this method returns false\&.
.PP
For a general explanation of what this method is good for in the context of the data container, see the documentation of \fBQCPDataContainer\fP\&. 
.PP
Definition at line \fB5268\fP of file \fBqcustomplot\&.h\fP\&.
.SS "\fBQCPRange\fP QCPCurveData::valueRange () const\fC [inline]\fP"
Returns a \fBQCPRange\fP with both lower and upper boundary set to \fIvalue\fP of this data point\&.
.PP
For a general explanation of what this method is good for in the context of the data container, see the documentation of \fBQCPDataContainer\fP\&. 
.PP
Definition at line \fB5273\fP of file \fBqcustomplot\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double QCPCurveData::key"

.PP
Definition at line \fB5275\fP of file \fBqcustomplot\&.h\fP\&.
.SS "double QCPCurveData::t"

.PP
Definition at line \fB5275\fP of file \fBqcustomplot\&.h\fP\&.
.SS "double QCPCurveData::value"

.PP
Definition at line \fB5275\fP of file \fBqcustomplot\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OmronPID from the source code\&.
