.TH "QCPColorMapData" 3 "Wed Mar 15 2023" "OmronPID" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QCPColorMapData \- Holds the two-dimensional data of a \fBQCPColorMap\fP plottable\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQCPColorMapData\fP (int keySize, int valueSize, const \fBQCPRange\fP &keyRange, const \fBQCPRange\fP &valueRange)"
.br
.ti -1c
.RI "\fBQCPColorMapData\fP (const \fBQCPColorMapData\fP &other)"
.br
.ti -1c
.RI "\fBQCPColorMapData\fP & \fBoperator=\fP (const \fBQCPColorMapData\fP &other)"
.br
.ti -1c
.RI "int \fBkeySize\fP () const"
.br
.ti -1c
.RI "int \fBvalueSize\fP () const"
.br
.ti -1c
.RI "\fBQCPRange\fP \fBkeyRange\fP () const"
.br
.ti -1c
.RI "\fBQCPRange\fP \fBvalueRange\fP () const"
.br
.ti -1c
.RI "\fBQCPRange\fP \fBdataBounds\fP () const"
.br
.ti -1c
.RI "double \fBdata\fP (double key, double value)"
.br
.ti -1c
.RI "double \fBcell\fP (int keyIndex, int valueIndex)"
.br
.ti -1c
.RI "unsigned char \fBalpha\fP (int keyIndex, int valueIndex)"
.br
.ti -1c
.RI "void \fBsetSize\fP (int keySize, int valueSize)"
.br
.ti -1c
.RI "void \fBsetKeySize\fP (int keySize)"
.br
.ti -1c
.RI "void \fBsetValueSize\fP (int valueSize)"
.br
.ti -1c
.RI "void \fBsetRange\fP (const \fBQCPRange\fP &keyRange, const \fBQCPRange\fP &valueRange)"
.br
.ti -1c
.RI "void \fBsetKeyRange\fP (const \fBQCPRange\fP &keyRange)"
.br
.ti -1c
.RI "void \fBsetValueRange\fP (const \fBQCPRange\fP &valueRange)"
.br
.ti -1c
.RI "void \fBsetData\fP (double key, double value, double z)"
.br
.ti -1c
.RI "void \fBsetCell\fP (int keyIndex, int valueIndex, double z)"
.br
.ti -1c
.RI "void \fBsetAlpha\fP (int keyIndex, int valueIndex, unsigned char \fBalpha\fP)"
.br
.ti -1c
.RI "void \fBrecalculateDataBounds\fP ()"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBclearAlpha\fP ()"
.br
.ti -1c
.RI "void \fBfill\fP (double z)"
.br
.ti -1c
.RI "void \fBfillAlpha\fP (unsigned char \fBalpha\fP)"
.br
.ti -1c
.RI "bool \fBisEmpty\fP () const"
.br
.ti -1c
.RI "void \fBcoordToCell\fP (double key, double value, int *keyIndex, int *valueIndex) const"
.br
.ti -1c
.RI "void \fBcellToCoord\fP (int keyIndex, int valueIndex, double *key, double *value) const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fBcreateAlpha\fP (bool initializeOpaque=true)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBmKeySize\fP"
.br
.ti -1c
.RI "int \fBmValueSize\fP"
.br
.ti -1c
.RI "\fBQCPRange\fP \fBmKeyRange\fP"
.br
.ti -1c
.RI "\fBQCPRange\fP \fBmValueRange\fP"
.br
.ti -1c
.RI "bool \fBmIsEmpty\fP"
.br
.ti -1c
.RI "double * \fBmData\fP"
.br
.ti -1c
.RI "unsigned char * \fBmAlpha\fP"
.br
.ti -1c
.RI "\fBQCPRange\fP \fBmDataBounds\fP"
.br
.ti -1c
.RI "bool \fBmDataModified\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBQCPColorMap\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds the two-dimensional data of a \fBQCPColorMap\fP plottable\&. 

This class is a data storage for \fBQCPColorMap\fP\&. It holds a two-dimensional array, which \fBQCPColorMap\fP then displays as a 2D image in the plot, where the array values are represented by a color, depending on the value\&.
.PP
The size of the array can be controlled via \fBsetSize\fP (or \fBsetKeySize\fP, \fBsetValueSize\fP)\&. Which plot coordinates these cells correspond to can be configured with \fBsetRange\fP (or \fBsetKeyRange\fP, \fBsetValueRange\fP)\&.
.PP
The data cells can be accessed in two ways: They can be directly addressed by an integer index with \fBsetCell\fP\&. This is the fastest method\&. Alternatively, they can be addressed by their plot coordinate with \fBsetData\fP\&. plot coordinate to cell index transformations and vice versa are provided by the functions \fBcoordToCell\fP and \fBcellToCoord\fP\&.
.PP
A \fBQCPColorMapData\fP also holds an on-demand two-dimensional array of alpha values which (if allocated) has the same size as the data map\&. It can be accessed via \fBsetAlpha\fP, \fBfillAlpha\fP and \fBclearAlpha\fP\&. The memory for the alpha map is only allocated if needed, i\&.e\&. on the first call of \fBsetAlpha\fP\&. \fBclearAlpha\fP restores full opacity and frees the alpha map\&.
.PP
This class also buffers the minimum and maximum values that are in the data set, to provide \fBQCPColorMap::rescaleDataRange\fP with the necessary information quickly\&. Setting a cell to a value that is greater than the current maximum increases this maximum to the new value\&. However, setting the cell that currently holds the maximum value to a smaller value doesn't decrease the maximum again, because finding the true new maximum would require going through the entire data array, which might be time consuming\&. The same holds for the data minimum\&. This functionality is given by \fBrecalculateDataBounds\fP, such that you can decide when it is sensible to find the true current minimum and maximum\&. The method \fBQCPColorMap::rescaleDataRange\fP offers a convenience parameter \fIrecalculateDataBounds\fP which may be set to true to automatically call \fBrecalculateDataBounds\fP internally\&. 
.PP
Definition at line \fB5680\fP of file \fBqcustomplot\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QCPColorMapData::QCPColorMapData (int keySize, int valueSize, const \fBQCPRange\fP & keyRange, const \fBQCPRange\fP & valueRange)"
Constructs a new \fBQCPColorMapData\fP instance\&. The instance has \fIkeySize\fP cells in the key direction and \fIvalueSize\fP cells in the value direction\&. These cells will be displayed by the \fBQCPColorMap\fP at the coordinates \fIkeyRange\fP and \fIvalueRange\fP\&.
.PP
\fBSee also\fP
.RS 4
\fBsetSize\fP, \fBsetKeySize\fP, \fBsetValueSize\fP, \fBsetRange\fP, \fBsetKeyRange\fP, \fBsetValueRange\fP 
.RE
.PP

.PP
Definition at line \fB24978\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "QCPColorMapData::~QCPColorMapData ()"

.PP
Definition at line \fB24992\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "QCPColorMapData::QCPColorMapData (const \fBQCPColorMapData\fP & other)"
Constructs a new \fBQCPColorMapData\fP instance copying the data and range of \fIother\fP\&. 
.PP
Definition at line \fB25003\fP of file \fBqcustomplot\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "unsigned char QCPColorMapData::alpha (int keyIndex, int valueIndex)"
Returns the alpha map value of the cell with the indices \fIkeyIndex\fP and \fIvalueIndex\fP\&.
.PP
If this color map data doesn't have an alpha map (because \fBsetAlpha\fP was never called after creation or after a call to \fBclearAlpha\fP), returns 255, which corresponds to full opacity\&.
.PP
\fBSee also\fP
.RS 4
\fBsetAlpha\fP 
.RE
.PP

.PP
Definition at line \fB25070\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "double QCPColorMapData::cell (int keyIndex, int valueIndex)"

.PP
Definition at line \fB25054\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPColorMapData::cellToCoord (int keyIndex, int valueIndex, double * key, double * value) const"
Transforms cell indices given by \fIkeyIndex\fP and \fIvalueIndex\fP to cell indices of this \fBQCPColorMapData\fP instance\&. The resulting coordinates are returned via the output parameters \fIkey\fP and \fIvalue\fP\&.
.PP
If you are only interested in a key or value coordinate, you may pass 0 as \fIkey\fP or \fIvalue\fP\&.
.PP
\fBNote\fP
.RS 4
The \fBQCPColorMap\fP always displays the data at equal key/value intervals, even if the key or value axis is set to a logarithmic scaling\&. If you want to use \fBQCPColorMap\fP with logarithmic axes, you shouldn't use the \fBQCPColorMapData::cellToCoord\fP method as it uses a linear transformation to determine the cell index\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBcoordToCell\fP, \fBQCPAxis::pixelToCoord\fP 
.RE
.PP

.PP
Definition at line \fB25405\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPColorMapData::clear ()"
Frees the internal data memory\&.
.PP
This is equivalent to calling \fBsetSize(0, 0)\fP\&. 
.PP
Definition at line \fB25315\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPColorMapData::clearAlpha ()"
Frees the internal alpha map\&. The color map will have full opacity again\&. 
.PP
Definition at line \fB25323\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPColorMapData::coordToCell (double key, double value, int * keyIndex, int * valueIndex) const"
Transforms plot coordinates given by \fIkey\fP and \fIvalue\fP to cell indices of this \fBQCPColorMapData\fP instance\&. The resulting cell indices are returned via the output parameters \fIkeyIndex\fP and \fIvalueIndex\fP\&.
.PP
The retrieved key/value cell indices can then be used for example with \fBsetCell\fP\&.
.PP
If you are only interested in a key or value index, you may pass 0 as \fIvalueIndex\fP or \fIkeyIndex\fP\&.
.PP
\fBNote\fP
.RS 4
The \fBQCPColorMap\fP always displays the data at equal key/value intervals, even if the key or value axis is set to a logarithmic scaling\&. If you want to use \fBQCPColorMap\fP with logarithmic axes, you shouldn't use the \fBQCPColorMapData::coordToCell\fP method as it uses a linear transformation to determine the cell index\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBcellToCoord\fP, \fBQCPAxis::coordToPixel\fP 
.RE
.PP

.PP
Definition at line \fB25382\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "bool QCPColorMapData::createAlpha (bool initializeOpaque = \fCtrue\fP)\fC [protected]\fP"

.PP
Definition at line \fB25426\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "double QCPColorMapData::data (double key, double value)"

.PP
Definition at line \fB25043\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "\fBQCPRange\fP QCPColorMapData::dataBounds () const\fC [inline]\fP"

.PP
Definition at line \fB5693\fP of file \fBqcustomplot\&.h\fP\&.
.SS "void QCPColorMapData::fill (double z)"
Sets all cells to the value \fIz\fP\&. 
.PP
Definition at line \fB25336\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPColorMapData::fillAlpha (unsigned char alpha)"
Sets the opacity of all color map cells to \fIalpha\fP\&. A value of 0 for \fIalpha\fP results in a fully transparent color map, and a value of 255 results in a fully opaque color map\&.
.PP
If you wish to restore opacity to 100% and free any used memory for the alpha map, rather use \fBclearAlpha\fP\&.
.PP
\fBSee also\fP
.RS 4
\fBsetAlpha\fP 
.RE
.PP

.PP
Definition at line \fB25354\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "bool QCPColorMapData::isEmpty () const\fC [inline]\fP"
Returns whether this instance carries no data\&. This is equivalent to having a size where at least one of the dimensions is 0 (see \fBsetSize\fP)\&. 
.PP
Definition at line \fB5715\fP of file \fBqcustomplot\&.h\fP\&.
.SS "\fBQCPRange\fP QCPColorMapData::keyRange () const\fC [inline]\fP"

.PP
Definition at line \fB5691\fP of file \fBqcustomplot\&.h\fP\&.
.SS "int QCPColorMapData::keySize () const\fC [inline]\fP"

.PP
Definition at line \fB5689\fP of file \fBqcustomplot\&.h\fP\&.
.SS "\fBQCPColorMapData\fP & QCPColorMapData::operator= (const \fBQCPColorMapData\fP & other)"
Overwrites this color map data instance with the data stored in \fIother\fP\&. The alpha map state is transferred, too\&. 
.PP
Definition at line \fB25018\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPColorMapData::recalculateDataBounds ()"
Goes through the data and updates the buffered minimum and maximum data values\&.
.PP
Calling this method is only advised if you are about to call \fBQCPColorMap::rescaleDataRange\fP and can not guarantee that the cells holding the maximum or minimum data haven't been overwritten with a smaller or larger value respectively, since the buffered maximum/minimum values have been updated the last time\&. Why this is the case is explained in the class description (\fBQCPColorMapData\fP)\&.
.PP
Note that the method \fBQCPColorMap::rescaleDataRange\fP provides a parameter \fIrecalculateDataBounds\fP for convenience\&. Setting this to true will call this method for you, before doing the rescale\&. 
.PP
Definition at line \fB25291\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPColorMapData::setAlpha (int keyIndex, int valueIndex, unsigned char alpha)"
Sets the alpha of the color map cell given by \fIkeyIndex\fP and \fIvalueIndex\fP to \fIalpha\fP\&. A value of 0 for \fIalpha\fP results in a fully transparent cell, and a value of 255 results in a fully opaque cell\&.
.PP
If an alpha map doesn't exist yet for this color map data, it will be created here\&. If you wish to restore full opacity and free any allocated memory of the alpha map, call \fBclearAlpha\fP\&.
.PP
Note that the cell-wise alpha which can be configured here is independent of any alpha configured in the color map's gradient (\fBQCPColorGradient\fP)\&. If a cell is affected both by the cell-wise and gradient alpha, the alpha values will be blended accordingly during rendering of the color map\&.
.PP
\fBSee also\fP
.RS 4
\fBfillAlpha\fP, \fBclearAlpha\fP 
.RE
.PP

.PP
Definition at line \fB25265\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPColorMapData::setCell (int keyIndex, int valueIndex, double z)"
Sets the data of the cell with indices \fIkeyIndex\fP and \fIvalueIndex\fP to \fIz\fP\&. The indices enumerate the cells starting from zero, up to the map's size-1 in the respective dimension (see \fBsetSize\fP)\&.
.PP
In the standard plot configuration (horizontal key axis and vertical value axis, both not range-reversed), the cell with indices (0, 0) is in the bottom left corner and the cell with indices (keySize-1, valueSize-1) is in the top right corner of the color map\&.
.PP
\fBSee also\fP
.RS 4
\fBsetData\fP, \fBsetSize\fP 
.RE
.PP

.PP
Definition at line \fB25236\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPColorMapData::setData (double key, double value, double z)"
Sets the data of the cell, which lies at the plot coordinates given by \fIkey\fP and \fIvalue\fP, to \fIz\fP\&.
.PP
\fBNote\fP
.RS 4
The \fBQCPColorMap\fP always displays the data at equal key/value intervals, even if the key or value axis is set to a logarithmic scaling\&. If you want to use \fBQCPColorMap\fP with logarithmic axes, you shouldn't use the \fBQCPColorMapData::setData\fP method as it uses a linear transformation to determine the cell index\&. Rather directly access the cell index with \fBQCPColorMapData::setCell\fP\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBsetCell\fP, \fBsetRange\fP 
.RE
.PP

.PP
Definition at line \fB25210\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPColorMapData::setKeyRange (const \fBQCPRange\fP & keyRange)"
Sets the coordinate range the data shall be distributed over in the key dimension\&. Together with the value range, This defines the rectangular area covered by the color map in plot coordinates\&.
.PP
The outer cells will be centered on the range boundaries given to this function\&. For example, if the key size (\fBsetKeySize\fP) is 3 and \fIkeyRange\fP is set to \fC\fBQCPRange(2, 3)\fP\fP there will be cells centered on the key coordinates 2, 2\&.5 and 3\&.
.PP
\fBSee also\fP
.RS 4
\fBsetRange\fP, \fBsetValueRange\fP, \fBsetSize\fP 
.RE
.PP

.PP
Definition at line \fB25178\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPColorMapData::setKeySize (int keySize)"
Resizes the data array to have \fIkeySize\fP cells in the key dimension\&.
.PP
The current data is discarded and the map cells are set to 0, unless the map had already the requested size\&.
.PP
Setting \fIkeySize\fP to zero frees the internal data array and \fBisEmpty\fP returns true\&.
.PP
\fBSee also\fP
.RS 4
\fBsetKeyRange\fP, \fBsetSize\fP, \fBsetValueSize\fP 
.RE
.PP

.PP
Definition at line \fB25132\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPColorMapData::setRange (const \fBQCPRange\fP & keyRange, const \fBQCPRange\fP & valueRange)"
Sets the coordinate ranges the data shall be distributed over\&. This defines the rectangular area covered by the color map in plot coordinates\&.
.PP
The outer cells will be centered on the range boundaries given to this function\&. For example, if the key size (\fBsetKeySize\fP) is 3 and \fIkeyRange\fP is set to \fC\fBQCPRange(2, 3)\fP\fP there will be cells centered on the key coordinates 2, 2\&.5 and 3\&.
.PP
\fBSee also\fP
.RS 4
\fBsetSize\fP 
.RE
.PP

.PP
Definition at line \fB25162\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPColorMapData::setSize (int keySize, int valueSize)"
Resizes the data array to have \fIkeySize\fP cells in the key dimension and \fIvalueSize\fP cells in the value dimension\&.
.PP
The current data is discarded and the map cells are set to 0, unless the map had already the requested size\&.
.PP
Setting at least one of \fIkeySize\fP or \fIvalueSize\fP to zero frees the internal data array and \fBisEmpty\fP returns true\&.
.PP
\fBSee also\fP
.RS 4
\fBsetRange\fP, \fBsetKeySize\fP, \fBsetValueSize\fP 
.RE
.PP

.PP
Definition at line \fB25090\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPColorMapData::setValueRange (const \fBQCPRange\fP & valueRange)"
Sets the coordinate range the data shall be distributed over in the value dimension\&. Together with the key range, This defines the rectangular area covered by the color map in plot coordinates\&.
.PP
The outer cells will be centered on the range boundaries given to this function\&. For example, if the value size (\fBsetValueSize\fP) is 3 and \fIvalueRange\fP is set to \fC\fBQCPRange(2, 3)\fP\fP there will be cells centered on the value coordinates 2, 2\&.5 and 3\&.
.PP
\fBSee also\fP
.RS 4
\fBsetRange\fP, \fBsetKeyRange\fP, \fBsetSize\fP 
.RE
.PP

.PP
Definition at line \fB25193\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPColorMapData::setValueSize (int valueSize)"
Resizes the data array to have \fIvalueSize\fP cells in the value dimension\&.
.PP
The current data is discarded and the map cells are set to 0, unless the map had already the requested size\&.
.PP
Setting \fIvalueSize\fP to zero frees the internal data array and \fBisEmpty\fP returns true\&.
.PP
\fBSee also\fP
.RS 4
\fBsetValueRange\fP, \fBsetSize\fP, \fBsetKeySize\fP 
.RE
.PP

.PP
Definition at line \fB25147\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "\fBQCPRange\fP QCPColorMapData::valueRange () const\fC [inline]\fP"

.PP
Definition at line \fB5692\fP of file \fBqcustomplot\&.h\fP\&.
.SS "int QCPColorMapData::valueSize () const\fC [inline]\fP"

.PP
Definition at line \fB5690\fP of file \fBqcustomplot\&.h\fP\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBQCPColorMap\fP\fC [friend]\fP"

.PP
Definition at line \fB5733\fP of file \fBqcustomplot\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned char* QCPColorMapData::mAlpha\fC [protected]\fP"

.PP
Definition at line \fB5727\fP of file \fBqcustomplot\&.h\fP\&.
.SS "double* QCPColorMapData::mData\fC [protected]\fP"

.PP
Definition at line \fB5726\fP of file \fBqcustomplot\&.h\fP\&.
.SS "\fBQCPRange\fP QCPColorMapData::mDataBounds\fC [protected]\fP"

.PP
Definition at line \fB5728\fP of file \fBqcustomplot\&.h\fP\&.
.SS "bool QCPColorMapData::mDataModified\fC [protected]\fP"

.PP
Definition at line \fB5729\fP of file \fBqcustomplot\&.h\fP\&.
.SS "bool QCPColorMapData::mIsEmpty\fC [protected]\fP"

.PP
Definition at line \fB5723\fP of file \fBqcustomplot\&.h\fP\&.
.SS "\fBQCPRange\fP QCPColorMapData::mKeyRange\fC [protected]\fP"

.PP
Definition at line \fB5722\fP of file \fBqcustomplot\&.h\fP\&.
.SS "int QCPColorMapData::mKeySize\fC [protected]\fP"

.PP
Definition at line \fB5721\fP of file \fBqcustomplot\&.h\fP\&.
.SS "\fBQCPRange\fP QCPColorMapData::mValueRange\fC [protected]\fP"

.PP
Definition at line \fB5722\fP of file \fBqcustomplot\&.h\fP\&.
.SS "int QCPColorMapData::mValueSize\fC [protected]\fP"

.PP
Definition at line \fB5721\fP of file \fBqcustomplot\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OmronPID from the source code\&.
