.TH "QCPDataContainer< DataType >" 3 "Wed Mar 15 2023" "OmronPID" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QCPDataContainer< DataType > \- The generic data container for one-dimensional plottables\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qcustomplot\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef QVector< DataType >::const_iterator \fBconst_iterator\fP"
.br
.ti -1c
.RI "typedef QVector< DataType >::iterator \fBiterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQCPDataContainer\fP ()"
.br
.ti -1c
.RI "int \fBsize\fP () const"
.br
.ti -1c
.RI "bool \fBisEmpty\fP () const"
.br
.ti -1c
.RI "bool \fBautoSqueeze\fP () const"
.br
.ti -1c
.RI "void \fBsetAutoSqueeze\fP (bool enabled)"
.br
.ti -1c
.RI "void \fBset\fP (const \fBQCPDataContainer\fP< DataType > &data)"
.br
.ti -1c
.RI "void \fBset\fP (const QVector< DataType > &data, bool alreadySorted=false)"
.br
.ti -1c
.RI "void \fBadd\fP (const \fBQCPDataContainer\fP< DataType > &data)"
.br
.ti -1c
.RI "void \fBadd\fP (const QVector< DataType > &data, bool alreadySorted=false)"
.br
.ti -1c
.RI "void \fBadd\fP (const DataType &data)"
.br
.ti -1c
.RI "void \fBremoveBefore\fP (double sortKey)"
.br
.ti -1c
.RI "void \fBremoveAfter\fP (double sortKey)"
.br
.ti -1c
.RI "void \fBremove\fP (double sortKeyFrom, double sortKeyTo)"
.br
.ti -1c
.RI "void \fBremove\fP (double sortKey)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBsort\fP ()"
.br
.ti -1c
.RI "void \fBsqueeze\fP (bool preAllocation=true, bool postAllocation=true)"
.br
.ti -1c
.RI "const_iterator \fBconstBegin\fP () const"
.br
.ti -1c
.RI "const_iterator \fBconstEnd\fP () const"
.br
.ti -1c
.RI "iterator \fBbegin\fP ()"
.br
.ti -1c
.RI "iterator \fBend\fP ()"
.br
.ti -1c
.RI "const_iterator \fBfindBegin\fP (double sortKey, bool expandedRange=true) const"
.br
.ti -1c
.RI "const_iterator \fBfindEnd\fP (double sortKey, bool expandedRange=true) const"
.br
.ti -1c
.RI "const_iterator \fBat\fP (int index) const"
.br
.ti -1c
.RI "\fBQCPRange\fP \fBkeyRange\fP (bool &foundRange, \fBQCP::SignDomain\fP signDomain=\fBQCP::sdBoth\fP)"
.br
.ti -1c
.RI "\fBQCPRange\fP \fBvalueRange\fP (bool &foundRange, \fBQCP::SignDomain\fP signDomain=\fBQCP::sdBoth\fP, const \fBQCPRange\fP &inKeyRange=\fBQCPRange\fP())"
.br
.ti -1c
.RI "\fBQCPDataRange\fP \fBdataRange\fP () const"
.br
.ti -1c
.RI "void \fBlimitIteratorsToDataRange\fP (const_iterator &\fBbegin\fP, const_iterator &\fBend\fP, const \fBQCPDataRange\fP &\fBdataRange\fP) const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBpreallocateGrow\fP (int minimumPreallocSize)"
.br
.ti -1c
.RI "void \fBperformAutoSqueeze\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBmAutoSqueeze\fP"
.br
.ti -1c
.RI "QVector< DataType > \fBmData\fP"
.br
.ti -1c
.RI "int \fBmPreallocSize\fP"
.br
.ti -1c
.RI "int \fBmPreallocIteration\fP"
.br
.in -1c
.SS "Related Functions"
(Note that these are not member functions\&.) 
.in +1c
.ti -1c
.RI "template<class DataType > bool \fBqcpLessThanSortKey\fP (const DataType &a, const DataType &b)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class DataType>
.br
class QCPDataContainer< DataType >"The generic data container for one-dimensional plottables\&. 

This class template provides a fast container for data storage of one-dimensional data\&. The data type is specified as template parameter (called \fIDataType\fP in the following) and must provide some methods as described in the \fBnext section\fP\&.
.PP
The data is stored in a sorted fashion, which allows very quick lookups by the sorted key as well as retrieval of ranges (see \fBfindBegin\fP, \fBfindEnd\fP, \fBkeyRange\fP) using binary search\&. The container uses a preallocation and a postallocation scheme, such that appending and prepending data (with respect to the sort key) is very fast and minimizes reallocations\&. If data is added which needs to be inserted between existing keys, the merge usually can be done quickly too, using the fact that existing data is always sorted\&. The user can further improve performance by specifying that added data is already itself sorted by key, if he can guarantee that this is the case (see for example \fBadd(const QVector<DataType> &data, bool alreadySorted)\fP)\&.
.PP
The data can be accessed with the provided const iterators (\fBconstBegin\fP, \fBconstEnd\fP)\&. If it is necessary to alter existing data in-place, the non-const iterators can be used (\fBbegin\fP, \fBend\fP)\&. Changing data members that are not the sort key (for most data types called \fIkey\fP) is safe from the container's perspective\&.
.PP
Great care must be taken however if the sort key is modified through the non-const iterators\&. For performance reasons, the iterators don't automatically cause a re-sorting upon their manipulation\&. It is thus the responsibility of the user to leave the container in a sorted state when finished with the data manipulation, before calling any other methods on the container\&. A complete re-sort (e\&.g\&. after finishing all sort key manipulation) can be done by calling \fBsort\fP\&. Failing to do so can not be detected by the container efficiently and will cause both rendering artifacts and potential data loss\&.
.PP
Implementing one-dimensional plottables that make use of a \fBQCPDataContainer<T>\fP is usually done by subclassing from \fBQCPAbstractPlottable1D<T>\fP, which introduces an according \fImDataContainer\fP member and some convenience methods\&.
.SH "Requirements for the DataType template parameter"
.PP
The template parameter \fCDataType\fP is the type of the stored data points\&. It must be trivially copyable and have the following public methods, preferably inline:
.PP
.PD 0
.IP "\(bu" 2
\fCdouble sortKey() const\fP
.br
 Returns the member variable of this data point that is the sort key, defining the ordering in the container\&. Often this variable is simply called \fIkey\fP\&.
.PP
.PD 0
.IP "\(bu" 2
\fCstatic DataType fromSortKey(double sortKey)\fP
.br
 Returns a new instance of the data type initialized with its sort key set to \fIsortKey\fP\&.
.PP
.PD 0
.IP "\(bu" 2
\fCstatic bool sortKeyIsMainKey()\fP
.br
 Returns true if the sort key is equal to the main key (see method \fCmainKey\fP below)\&. For most plottables this is the case\&. It is not the case for example for \fBQCPCurve\fP, which uses \fIt\fP as sort key and \fIkey\fP as main key\&. This is the reason why \fBQCPCurve\fP unlike \fBQCPGraph\fP can display parametric curves with loops\&.
.PP
.PD 0
.IP "\(bu" 2
\fCdouble mainKey() const\fP
.br
 Returns the variable of this data point considered the main key\&. This is commonly the variable that is used as the coordinate of this data point on the key axis of the plottable\&. This method is used for example when determining the automatic axis rescaling of key axes (\fBQCPAxis::rescale\fP)\&.
.PP
.PD 0
.IP "\(bu" 2
\fCdouble mainValue() const\fP
.br
 Returns the variable of this data point considered the main value\&. This is commonly the variable that is used as the coordinate of this data point on the value axis of the plottable\&.
.PP
.PD 0
.IP "\(bu" 2
\fC\fBQCPRange\fP valueRange() const\fP
.br
 Returns the range this data point spans in the value axis coordinate\&. If the data is single-valued (e\&.g\&. \fBQCPGraphData\fP), this is simply a range with both lower and upper set to the main data point value\&. However if the data points can represent multiple values at once (e\&.g \fBQCPFinancialData\fP with its \fIhigh\fP, \fIlow\fP, \fIopen\fP and \fIclose\fP values at each \fIkey\fP) this method should return the range those values span\&. This method is used for example when determining the automatic axis rescaling of value axes (\fBQCPAxis::rescale\fP)\&. 
.PP

.PP
Definition at line \fB2404\fP of file \fBqcustomplot\&.h\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<class DataType > typedef QVector<DataType>::const_iterator \fBQCPDataContainer\fP< DataType >::const_iterator"

.PP
Definition at line \fB2407\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > typedef QVector<DataType>::iterator \fBQCPDataContainer\fP< DataType >::iterator"

.PP
Definition at line \fB2408\fP of file \fBqcustomplot\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class DataType > \fBQCPDataContainer\fP< DataType >\fB::QCPDataContainer\fP"
Constructs a \fBQCPDataContainer\fP used for plottable classes that represent a series of key-sorted data 
.PP
Definition at line \fB2599\fP of file \fBqcustomplot\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class DataType > void \fBQCPDataContainer\fP< DataType >::add (const DataType & data)"
This is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&.
.PP
Adds the provided single data point to the current data\&.
.PP
\fBSee also\fP
.RS 4
\fBremove\fP 
.RE
.PP

.PP
Definition at line \fB2733\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > void \fBQCPDataContainer\fP< DataType >::add (const \fBQCPDataContainer\fP< DataType > & data)"
This is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&.
.PP
Adds the provided \fIdata\fP to the current data in this container\&.
.PP
\fBSee also\fP
.RS 4
\fBset\fP, \fBremove\fP 
.RE
.PP

.PP
Definition at line \fB2664\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > void \fBQCPDataContainer\fP< DataType >::add (const QVector< DataType > & data, bool alreadySorted = \fCfalse\fP)"
Adds the provided data points in \fIdata\fP to the current data\&.
.PP
If you can guarantee that the data points in \fIdata\fP have ascending order with respect to the DataType's sort key, set \fIalreadySorted\fP to true to avoid an unnecessary sorting run\&.
.PP
\fBSee also\fP
.RS 4
\fBset\fP, \fBremove\fP 
.RE
.PP

.PP
Definition at line \fB2696\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > QCPDataContainer::const_iterator \fBQCPDataContainer\fP< DataType >::at (int index) const\fC [inline]\fP"
Returns a const iterator to the element with the specified \fIindex\fP\&. If \fIindex\fP points beyond the available elements in this container, returns \fBconstEnd\fP, i\&.e\&. an iterator past the last valid element\&.
.PP
You can use this method to easily obtain iterators from a \fBQCPDataRange\fP, see the \fBdata selection page\fP for an example\&. 
.PP
Definition at line \fB2440\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > bool \fBQCPDataContainer\fP< DataType >::autoSqueeze () const\fC [inline]\fP"

.PP
Definition at line \fB2415\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > QCPDataContainer::iterator \fBQCPDataContainer\fP< DataType >::begin ()\fC [inline]\fP"
Returns a non-const iterator to the first data point in this container\&.
.PP
You can manipulate the data points in-place through the non-const iterators, but great care must be taken when manipulating the sort key of a data point, see \fBsort\fP, or the detailed description of this class\&. 
.PP
Definition at line \fB2436\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > void \fBQCPDataContainer\fP< DataType >::clear"
Removes all data points\&.
.PP
\fBSee also\fP
.RS 4
\fBremove\fP, \fBremoveAfter\fP, \fBremoveBefore\fP 
.RE
.PP

.PP
Definition at line \fB2831\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > QCPDataContainer::const_iterator \fBQCPDataContainer\fP< DataType >::constBegin () const\fC [inline]\fP"
Returns a const iterator to the first data point in this container\&. 
.PP
Definition at line \fB2434\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > QCPDataContainer::const_iterator \fBQCPDataContainer\fP< DataType >::constEnd () const\fC [inline]\fP"
Returns a const iterator to the element past the last data point in this container\&. 
.PP
Definition at line \fB2435\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > \fBQCPDataRange\fP \fBQCPDataContainer\fP< DataType >::dataRange () const\fC [inline]\fP"
Returns a \fBQCPDataRange\fP encompassing the entire data set of this container\&. This means the begin index of the returned range is 0, and the end index is \fBsize\fP\&. 
.PP
Definition at line \fB2443\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > QCPDataContainer::iterator \fBQCPDataContainer\fP< DataType >::end ()\fC [inline]\fP"
Returns a non-const iterator to the element past the last data point in this container\&.
.PP
You can manipulate the data points in-place through the non-const iterators, but great care must be taken when manipulating the sort key of a data point, see \fBsort\fP, or the detailed description of this class\&. 
.PP
Definition at line \fB2437\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > \fBQCPDataContainer\fP< DataType >::const_iterator \fBQCPDataContainer\fP< DataType >::findBegin (double sortKey, bool expandedRange = \fCtrue\fP) const"
Returns an iterator to the data point with a (sort-)key that is equal to, just below, or just above \fIsortKey\fP\&. If \fIexpandedRange\fP is true, the data point just below \fIsortKey\fP will be considered, otherwise the one just above\&.
.PP
This can be used in conjunction with \fBfindEnd\fP to iterate over data points within a given key range, including or excluding the bounding data points that are just beyond the specified range\&.
.PP
If \fIexpandedRange\fP is true but there are no data points below \fIsortKey\fP, \fBconstBegin\fP is returned\&.
.PP
If the container is empty, returns \fBconstEnd\fP\&.
.PP
\fBSee also\fP
.RS 4
\fBfindEnd\fP, \fBQCPPlottableInterface1D::findBegin\fP 
.RE
.PP

.PP
Definition at line \fB2898\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > \fBQCPDataContainer\fP< DataType >::const_iterator \fBQCPDataContainer\fP< DataType >::findEnd (double sortKey, bool expandedRange = \fCtrue\fP) const"
Returns an iterator to the element after the data point with a (sort-)key that is equal to, just above or just below \fIsortKey\fP\&. If \fIexpandedRange\fP is true, the data point just above \fIsortKey\fP will be considered, otherwise the one just below\&.
.PP
This can be used in conjunction with \fBfindBegin\fP to iterate over data points within a given key range, including the bounding data points that are just below and above the specified range\&.
.PP
If \fIexpandedRange\fP is true but there are no data points above \fIsortKey\fP, \fBconstEnd\fP is returned\&.
.PP
If the container is empty, \fBconstEnd\fP is returned\&.
.PP
\fBSee also\fP
.RS 4
\fBfindBegin\fP, \fBQCPPlottableInterface1D::findEnd\fP 
.RE
.PP

.PP
Definition at line \fB2925\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > bool \fBQCPDataContainer\fP< DataType >::isEmpty () const\fC [inline]\fP"
Returns whether this container holds no data points\&. 
.PP
Definition at line \fB2414\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > \fBQCPRange\fP \fBQCPDataContainer\fP< DataType >::keyRange (bool & foundRange, \fBQCP::SignDomain\fP signDomain = \fC\fBQCP::sdBoth\fP\fP)"
Returns the range encompassed by the (main-)key coordinate of all data points\&. The output parameter \fIfoundRange\fP indicates whether a sensible range was found\&. If this is false, you should not use the returned \fBQCPRange\fP (e\&.g\&. the data container is empty or all points have the same key)\&.
.PP
Use \fIsignDomain\fP to control which sign of the key coordinates should be considered\&. This is relevant e\&.g\&. for logarithmic plots which can mathematically only display one sign domain at a time\&.
.PP
If the DataType reports that its main key is equal to the sort key (\fIsortKeyIsMainKey\fP), as is the case for most plottables, this method uses this fact and finds the range very quickly\&.
.PP
\fBSee also\fP
.RS 4
\fBvalueRange\fP 
.RE
.PP

.PP
Definition at line \fB2952\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > void \fBQCPDataContainer\fP< DataType >::limitIteratorsToDataRange (const_iterator & begin, const_iterator & end, const \fBQCPDataRange\fP & dataRange) const"
Makes sure \fIbegin\fP and \fIend\fP mark a data range that is both within the bounds of this data container's data, as well as within the specified \fIdataRange\fP\&. The initial range described by the passed iterators \fIbegin\fP and \fIend\fP is never expanded, only contracted if necessary\&.
.PP
This function doesn't require for \fIdataRange\fP to be within the bounds of this data container's valid range\&. 
.PP
Definition at line \fB3163\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > void \fBQCPDataContainer\fP< DataType >::performAutoSqueeze\fC [protected]\fP"

.PP
Definition at line \fB3211\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > void \fBQCPDataContainer\fP< DataType >::preallocateGrow (int minimumPreallocSize)\fC [protected]\fP"

.PP
Definition at line \fB3181\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > void \fBQCPDataContainer\fP< DataType >::remove (double sortKey)"
This is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&.
.PP
Removes a single data point at \fIsortKey\fP\&. If the position is not known with absolute (binary) precision, consider using \fBremove(double sortKeyFrom, double sortKeyTo)\fP with a small fuzziness interval around the suspected position, depeding on the precision with which the (sort-)key is known\&.
.PP
\fBSee also\fP
.RS 4
\fBremoveBefore\fP, \fBremoveAfter\fP, \fBclear\fP 
.RE
.PP

.PP
Definition at line \fB2811\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > void \fBQCPDataContainer\fP< DataType >::remove (double sortKeyFrom, double sortKeyTo)"
Removes all data points with (sort-)keys between \fIsortKeyFrom\fP and \fIsortKeyTo\fP\&. if \fIsortKeyFrom\fP is greater or equal to \fIsortKeyTo\fP, the function does nothing\&. To remove a single data point with known (sort-)key, use \fBremove(double sortKey)\fP\&.
.PP
\fBSee also\fP
.RS 4
\fBremoveBefore\fP, \fBremoveAfter\fP, \fBclear\fP 
.RE
.PP

.PP
Definition at line \fB2789\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > void \fBQCPDataContainer\fP< DataType >::removeAfter (double sortKey)"
Removes all data points with (sort-)keys greater than or equal to \fIsortKey\fP\&.
.PP
\fBSee also\fP
.RS 4
\fBremoveBefore\fP, \fBremove\fP, \fBclear\fP 
.RE
.PP

.PP
Definition at line \fB2772\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > void \fBQCPDataContainer\fP< DataType >::removeBefore (double sortKey)"
Removes all data points with (sort-)keys smaller than or equal to \fIsortKey\fP\&.
.PP
\fBSee also\fP
.RS 4
\fBremoveAfter\fP, \fBremove\fP, \fBclear\fP 
.RE
.PP

.PP
Definition at line \fB2757\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > void \fBQCPDataContainer\fP< DataType >::set (const \fBQCPDataContainer\fP< DataType > & data)"
This is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&.
.PP
Replaces the current data in this container with the provided \fIdata\fP\&.
.PP
\fBSee also\fP
.RS 4
\fBadd\fP, \fBremove\fP 
.RE
.PP

.PP
Definition at line \fB2632\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > void \fBQCPDataContainer\fP< DataType >::set (const QVector< DataType > & data, bool alreadySorted = \fCfalse\fP)"
This is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&.
.PP
Replaces the current data in this container with the provided \fIdata\fP 
.PP
If you can guarantee that the data points in \fIdata\fP have ascending order with respect to the DataType's sort key, set \fIalreadySorted\fP to true to avoid an unnecessary sorting run\&.
.PP
\fBSee also\fP
.RS 4
\fBadd\fP, \fBremove\fP 
.RE
.PP

.PP
Definition at line \fB2648\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > void \fBQCPDataContainer\fP< DataType >::setAutoSqueeze (bool enabled)"
Sets whether the container automatically decides when to release memory from its post- and preallocation pools when data points are removed\&. By default this is enabled and for typical applications shouldn't be changed\&.
.PP
If auto squeeze is disabled, you can manually decide when to release pre-/postallocation with \fBsqueeze\fP\&. 
.PP
Definition at line \fB2615\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > int \fBQCPDataContainer\fP< DataType >::size () const\fC [inline]\fP"
Returns the number of data points in the container\&. 
.PP
Definition at line \fB2413\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > void \fBQCPDataContainer\fP< DataType >::sort"
Re-sorts all data points in the container by their sort key\&.
.PP
When setting, adding or removing points using the \fBQCPDataContainer\fP interface (\fBset\fP, \fBadd\fP, \fBremove\fP, etc\&.), the container makes sure to always stay in a sorted state such that a full resort is never necessary\&. However, if you choose to directly manipulate the sort key on data points by accessing and modifying it through the non-const iterators (\fBbegin\fP, \fBend\fP), it is your responsibility to bring the container back into a sorted state before any other methods are called on it\&. This can be achieved by calling this method immediately after finishing the sort key manipulation\&. 
.PP
Definition at line \fB2850\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > void \fBQCPDataContainer\fP< DataType >::squeeze (bool preAllocation = \fCtrue\fP, bool postAllocation = \fCtrue\fP)"
Frees all unused memory that is currently in the preallocation and postallocation pools\&.
.PP
Note that \fBQCPDataContainer\fP automatically decides whether squeezing is necessary, if \fBsetAutoSqueeze\fP is left enabled\&. It should thus not be necessary to use this method for typical applications\&.
.PP
The parameters \fIpreAllocation\fP and \fIpostAllocation\fP control whether pre- and/or post allocation should be freed, respectively\&. 
.PP
Definition at line \fB2866\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > \fBQCPRange\fP \fBQCPDataContainer\fP< DataType >::valueRange (bool & foundRange, \fBQCP::SignDomain\fP signDomain = \fC\fBQCP::sdBoth\fP\fP, const \fBQCPRange\fP & inKeyRange = \fC\fBQCPRange\fP()\fP)"
Returns the range encompassed by the value coordinates of the data points in the specified key range (\fIinKeyRange\fP), using the full \fIDataType::valueRange\fP reported by the data points\&. The output parameter \fIfoundRange\fP indicates whether a sensible range was found\&. If this is false, you should not use the returned \fBQCPRange\fP (e\&.g\&. the data container is empty or all points have the same value)\&.
.PP
If \fIinKeyRange\fP has both lower and upper bound set to zero (is equal to \fC\fBQCPRange()\fP\fP), all data points are considered, without any restriction on the keys\&.
.PP
Use \fIsignDomain\fP to control which sign of the value coordinates should be considered\&. This is relevant e\&.g\&. for logarithmic plots which can mathematically only display one sign domain at a time\&.
.PP
\fBSee also\fP
.RS 4
\fBkeyRange\fP 
.RE
.PP

.PP
Definition at line \fB3075\fP of file \fBqcustomplot\&.h\fP\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "template<class DataType > bool qcpLessThanSortKey (const DataType & a, const DataType & b)\fC [related]\fP"
Returns whether the sort key of \fIa\fP is less than the sort key of \fIb\fP\&.
.PP
\fBSee also\fP
.RS 4
\fBQCPDataContainer::sort\fP 
.RE
.PP

.PP
Definition at line \fB2401\fP of file \fBqcustomplot\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "template<class DataType > bool \fBQCPDataContainer\fP< DataType >::mAutoSqueeze\fC [protected]\fP"

.PP
Definition at line \fB2448\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > QVector<DataType> \fBQCPDataContainer\fP< DataType >::mData\fC [protected]\fP"

.PP
Definition at line \fB2451\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > int \fBQCPDataContainer\fP< DataType >::mPreallocIteration\fC [protected]\fP"

.PP
Definition at line \fB2453\fP of file \fBqcustomplot\&.h\fP\&.
.SS "template<class DataType > int \fBQCPDataContainer\fP< DataType >::mPreallocSize\fC [protected]\fP"

.PP
Definition at line \fB2452\fP of file \fBqcustomplot\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OmronPID from the source code\&.
