.TH "QCPErrorBarsData" 3 "Wed Mar 15 2023" "OmronPID" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QCPErrorBarsData \- Holds the data of one single error bar for \fBQCPErrorBars\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQCPErrorBarsData\fP ()"
.br
.ti -1c
.RI "\fBQCPErrorBarsData\fP (double error)"
.br
.ti -1c
.RI "\fBQCPErrorBarsData\fP (double errorMinus, double errorPlus)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBerrorMinus\fP"
.br
.ti -1c
.RI "double \fBerrorPlus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds the data of one single error bar for \fBQCPErrorBars\fP\&. 

The stored data is: 
.PD 0

.IP "\(bu" 2
\fIerrorMinus:\fP how much the error bar extends towards negative coordinates from the data point position 
.IP "\(bu" 2
\fIerrorPlus:\fP how much the error bar extends towards positive coordinates from the data point position
.PP
The container for storing the error bar information is \fBQCPErrorBarsDataContainer\fP\&. It is a typedef for \fCQVector<\fBQCPErrorBarsData\fP>\fP\&.
.PP
\fBSee also\fP
.RS 4
QCPErrorBarsDataContainer 
.RE
.PP

.PP
Definition at line \fB5955\fP of file \fBqcustomplot\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QCPErrorBarsData::QCPErrorBarsData ()"
Constructs an error bar with errors set to zero\&. 
.PP
Definition at line \fB27036\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "QCPErrorBarsData::QCPErrorBarsData (double error)\fC [explicit]\fP"
Constructs an error bar with equal \fIerror\fP in both negative and positive direction\&. 
.PP
Definition at line \fB27045\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "QCPErrorBarsData::QCPErrorBarsData (double errorMinus, double errorPlus)"
Constructs an error bar with negative and positive errors set to \fIerrorMinus\fP and \fIerrorPlus\fP, respectively\&. 
.PP
Definition at line \fB27055\fP of file \fBqcustomplot\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double QCPErrorBarsData::errorMinus"

.PP
Definition at line \fB5962\fP of file \fBqcustomplot\&.h\fP\&.
.SS "double QCPErrorBarsData::errorPlus"

.PP
Definition at line \fB5962\fP of file \fBqcustomplot\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OmronPID from the source code\&.
