.TH "QCPItemPixmap" 3 "Wed Mar 15 2023" "OmronPID" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QCPItemPixmap \- An arbitrary pixmap\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBQCPAbstractItem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQCPItemPixmap\fP (\fBQCustomPlot\fP *parentPlot)"
.br
.ti -1c
.RI "QPixmap \fBpixmap\fP () const"
.br
.ti -1c
.RI "bool \fBscaled\fP () const"
.br
.ti -1c
.RI "Qt::AspectRatioMode \fBaspectRatioMode\fP () const"
.br
.ti -1c
.RI "Qt::TransformationMode \fBtransformationMode\fP () const"
.br
.ti -1c
.RI "QPen \fBpen\fP () const"
.br
.ti -1c
.RI "QPen \fBselectedPen\fP () const"
.br
.ti -1c
.RI "void \fBsetPixmap\fP (const QPixmap &pixmap)"
.br
.ti -1c
.RI "void \fBsetScaled\fP (bool scaled, Qt::AspectRatioMode aspectRatioMode=Qt::KeepAspectRatio, Qt::TransformationMode transformationMode=Qt::SmoothTransformation)"
.br
.ti -1c
.RI "void \fBsetPen\fP (const QPen &pen)"
.br
.ti -1c
.RI "void \fBsetSelectedPen\fP (const QPen &pen)"
.br
.ti -1c
.RI "virtual double \fBselectTest\fP (const QPointF &pos, bool onlySelectable, QVariant *details=0) const Q_DECL_OVERRIDE"
.br
.in -1c

Public Member Functions inherited from \fBQCPAbstractItem\fP
.in +1c
.ti -1c
.RI "\fBQCPAbstractItem\fP (\fBQCustomPlot\fP *parentPlot)"
.br
.ti -1c
.RI "bool \fBclipToAxisRect\fP () const"
.br
.ti -1c
.RI "\fBQCPAxisRect\fP * \fBclipAxisRect\fP () const"
.br
.ti -1c
.RI "bool \fBselectable\fP () const"
.br
.ti -1c
.RI "bool \fBselected\fP () const"
.br
.ti -1c
.RI "void \fBsetClipToAxisRect\fP (bool clip)"
.br
.ti -1c
.RI "void \fBsetClipAxisRect\fP (\fBQCPAxisRect\fP *rect)"
.br
.ti -1c
.RI "Q_SLOT void \fBsetSelectable\fP (bool selectable)"
.br
.ti -1c
.RI "Q_SLOT void \fBsetSelected\fP (bool selected)"
.br
.ti -1c
.RI "virtual double \fBselectTest\fP (const QPointF &pos, bool onlySelectable, QVariant *details=0) const Q_DECL_OVERRIDE=0"
.br
.ti -1c
.RI "QList< \fBQCPItemPosition\fP * > \fBpositions\fP () const"
.br
.ti -1c
.RI "QList< \fBQCPItemAnchor\fP * > \fBanchors\fP () const"
.br
.ti -1c
.RI "\fBQCPItemPosition\fP * \fBposition\fP (const QString &name) const"
.br
.ti -1c
.RI "\fBQCPItemAnchor\fP * \fBanchor\fP (const QString &name) const"
.br
.ti -1c
.RI "bool \fBhasAnchor\fP (const QString &name) const"
.br
.in -1c

Public Member Functions inherited from \fBQCPLayerable\fP
.in +1c
.ti -1c
.RI "\fBQCPLayerable\fP (\fBQCustomPlot\fP *plot, QString targetLayer=QString(), \fBQCPLayerable\fP *\fBparentLayerable\fP=0)"
.br
.ti -1c
.RI "bool \fBvisible\fP () const"
.br
.ti -1c
.RI "\fBQCustomPlot\fP * \fBparentPlot\fP () const"
.br
.ti -1c
.RI "\fBQCPLayerable\fP * \fBparentLayerable\fP () const"
.br
.ti -1c
.RI "\fBQCPLayer\fP * \fBlayer\fP () const"
.br
.ti -1c
.RI "bool \fBantialiased\fP () const"
.br
.ti -1c
.RI "void \fBsetVisible\fP (bool on)"
.br
.ti -1c
.RI "Q_SLOT bool \fBsetLayer\fP (\fBQCPLayer\fP *layer)"
.br
.ti -1c
.RI "bool \fBsetLayer\fP (const QString &layerName)"
.br
.ti -1c
.RI "void \fBsetAntialiased\fP (bool enabled)"
.br
.ti -1c
.RI "virtual double \fBselectTest\fP (const QPointF &pos, bool onlySelectable, QVariant *details=0) const"
.br
.ti -1c
.RI "bool \fBrealVisibility\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBQCPItemPosition\fP *const \fBtopLeft\fP"
.br
.ti -1c
.RI "\fBQCPItemPosition\fP *const \fBbottomRight\fP"
.br
.ti -1c
.RI "\fBQCPItemAnchor\fP *const \fBtop\fP"
.br
.ti -1c
.RI "\fBQCPItemAnchor\fP *const \fBtopRight\fP"
.br
.ti -1c
.RI "\fBQCPItemAnchor\fP *const \fBright\fP"
.br
.ti -1c
.RI "\fBQCPItemAnchor\fP *const \fBbottom\fP"
.br
.ti -1c
.RI "\fBQCPItemAnchor\fP *const \fBbottomLeft\fP"
.br
.ti -1c
.RI "\fBQCPItemAnchor\fP *const \fBleft\fP"
.br
.in -1c
.SS "Protected Types"

.in +1c
.ti -1c
.RI "enum \fBAnchorIndex\fP { \fBaiTop\fP, \fBaiTopRight\fP, \fBaiRight\fP, \fBaiBottom\fP, \fBaiBottomLeft\fP, \fBaiLeft\fP }"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBdraw\fP (\fBQCPPainter\fP *painter) Q_DECL_OVERRIDE"
.br
.ti -1c
.RI "virtual QPointF \fBanchorPixelPosition\fP (int anchorId) const Q_DECL_OVERRIDE"
.br
.ti -1c
.RI "void \fBupdateScaledPixmap\fP (QRect finalRect=QRect(), bool flipHorz=false, bool flipVert=false)"
.br
.ti -1c
.RI "QRect \fBgetFinalRect\fP (bool *flippedHorz=0, bool *flippedVert=0) const"
.br
.ti -1c
.RI "QPen \fBmainPen\fP () const"
.br
.in -1c

Protected Member Functions inherited from \fBQCPAbstractItem\fP
.in +1c
.ti -1c
.RI "virtual \fBQCP::Interaction\fP \fBselectionCategory\fP () const Q_DECL_OVERRIDE"
.br
.ti -1c
.RI "virtual QRect \fBclipRect\fP () const Q_DECL_OVERRIDE"
.br
.ti -1c
.RI "virtual void \fBapplyDefaultAntialiasingHint\fP (\fBQCPPainter\fP *painter) const Q_DECL_OVERRIDE"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (\fBQCPPainter\fP *painter) Q_DECL_OVERRIDE=0"
.br
.ti -1c
.RI "virtual void \fBselectEvent\fP (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged) Q_DECL_OVERRIDE"
.br
.ti -1c
.RI "virtual void \fBdeselectEvent\fP (bool *selectionStateChanged) Q_DECL_OVERRIDE"
.br
.ti -1c
.RI "virtual QPointF \fBanchorPixelPosition\fP (int anchorId) const"
.br
.ti -1c
.RI "double \fBrectDistance\fP (const QRectF &rect, const QPointF &pos, bool filledRect) const"
.br
.ti -1c
.RI "\fBQCPItemPosition\fP * \fBcreatePosition\fP (const QString &name)"
.br
.ti -1c
.RI "\fBQCPItemAnchor\fP * \fBcreateAnchor\fP (const QString &name, int anchorId)"
.br
.in -1c

Protected Member Functions inherited from \fBQCPLayerable\fP
.in +1c
.ti -1c
.RI "virtual void \fBparentPlotInitialized\fP (\fBQCustomPlot\fP *parentPlot)"
.br
.ti -1c
.RI "virtual \fBQCP::Interaction\fP \fBselectionCategory\fP () const"
.br
.ti -1c
.RI "virtual QRect \fBclipRect\fP () const"
.br
.ti -1c
.RI "virtual void \fBapplyDefaultAntialiasingHint\fP (\fBQCPPainter\fP *painter) const =0"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (\fBQCPPainter\fP *painter)=0"
.br
.ti -1c
.RI "virtual void \fBselectEvent\fP (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)"
.br
.ti -1c
.RI "virtual void \fBdeselectEvent\fP (bool *selectionStateChanged)"
.br
.ti -1c
.RI "virtual void \fBmousePressEvent\fP (QMouseEvent *event, const QVariant &details)"
.br
.ti -1c
.RI "virtual void \fBmouseMoveEvent\fP (QMouseEvent *event, const QPointF &startPos)"
.br
.ti -1c
.RI "virtual void \fBmouseReleaseEvent\fP (QMouseEvent *event, const QPointF &startPos)"
.br
.ti -1c
.RI "virtual void \fBmouseDoubleClickEvent\fP (QMouseEvent *event, const QVariant &details)"
.br
.ti -1c
.RI "virtual void \fBwheelEvent\fP (QWheelEvent *event)"
.br
.ti -1c
.RI "void \fBinitializeParentPlot\fP (\fBQCustomPlot\fP *parentPlot)"
.br
.ti -1c
.RI "void \fBsetParentLayerable\fP (\fBQCPLayerable\fP *\fBparentLayerable\fP)"
.br
.ti -1c
.RI "bool \fBmoveToLayer\fP (\fBQCPLayer\fP *layer, bool prepend)"
.br
.ti -1c
.RI "void \fBapplyAntialiasingHint\fP (\fBQCPPainter\fP *painter, bool localAntialiased, \fBQCP::AntialiasedElement\fP overrideElement) const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "QPixmap \fBmPixmap\fP"
.br
.ti -1c
.RI "QPixmap \fBmScaledPixmap\fP"
.br
.ti -1c
.RI "bool \fBmScaled\fP"
.br
.ti -1c
.RI "bool \fBmScaledPixmapInvalidated\fP"
.br
.ti -1c
.RI "Qt::AspectRatioMode \fBmAspectRatioMode\fP"
.br
.ti -1c
.RI "Qt::TransformationMode \fBmTransformationMode\fP"
.br
.ti -1c
.RI "QPen \fBmPen\fP"
.br
.ti -1c
.RI "QPen \fBmSelectedPen\fP"
.br
.in -1c

Protected Attributes inherited from \fBQCPAbstractItem\fP
.in +1c
.ti -1c
.RI "bool \fBmClipToAxisRect\fP"
.br
.ti -1c
.RI "QPointer< \fBQCPAxisRect\fP > \fBmClipAxisRect\fP"
.br
.ti -1c
.RI "QList< \fBQCPItemPosition\fP * > \fBmPositions\fP"
.br
.ti -1c
.RI "QList< \fBQCPItemAnchor\fP * > \fBmAnchors\fP"
.br
.ti -1c
.RI "bool \fBmSelectable\fP"
.br
.ti -1c
.RI "bool \fBmSelected\fP"
.br
.in -1c

Protected Attributes inherited from \fBQCPLayerable\fP
.in +1c
.ti -1c
.RI "bool \fBmVisible\fP"
.br
.ti -1c
.RI "\fBQCustomPlot\fP * \fBmParentPlot\fP"
.br
.ti -1c
.RI "QPointer< \fBQCPLayerable\fP > \fBmParentLayerable\fP"
.br
.ti -1c
.RI "\fBQCPLayer\fP * \fBmLayer\fP"
.br
.ti -1c
.RI "bool \fBmAntialiased\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Signals inherited from \fBQCPAbstractItem\fP
.in +1c
.ti -1c
.RI "void \fBselectionChanged\fP (bool selected)"
.br
.ti -1c
.RI "void \fBselectableChanged\fP (bool selectable)"
.br
.in -1c

Signals inherited from \fBQCPLayerable\fP
.in +1c
.ti -1c
.RI "void \fBlayerChanged\fP (\fBQCPLayer\fP *newLayer)"
.br
.in -1c
.SH "Detailed Description"
.PP 
An arbitrary pixmap\&. 


.PP
It has two positions, \fItopLeft\fP and \fIbottomRight\fP, which define the rectangle the pixmap will be drawn in\&. Depending on the scale setting (\fBsetScaled\fP), the pixmap will be either scaled to fit the rectangle or be drawn aligned to the topLeft position\&.
.PP
If scaling is enabled and \fItopLeft\fP is further to the bottom/right than \fIbottomRight\fP (as shown on the right side of the example image), the pixmap will be flipped in the respective orientations\&. 
.PP
Definition at line \fB6442\fP of file \fBqcustomplot\&.h\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum QCPItemPixmap::AnchorIndex\fC [protected]\fP"

.PP
Definition at line \fB6484\fP of file \fBqcustomplot\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QCPItemPixmap::QCPItemPixmap (\fBQCustomPlot\fP * parentPlot)\fC [explicit]\fP"
Creates a rectangle item and sets default values\&.
.PP
The created item is automatically registered with \fIparentPlot\fP\&. This \fBQCustomPlot\fP instance takes ownership of the item, so do not delete it manually but use \fBQCustomPlot::removeItem()\fP instead\&. 
.PP
Definition at line \fB29269\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "QCPItemPixmap::~QCPItemPixmap ()\fC [virtual]\fP"

.PP
Definition at line \fB29291\fP of file \fBqcustomplot\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "QPointF QCPItemPixmap::anchorPixelPosition (int anchorId) const\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBQCPAbstractItem\fP\&.
.PP
Definition at line \fB29371\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "Qt::AspectRatioMode QCPItemPixmap::aspectRatioMode () const\fC [inline]\fP"

.PP
Definition at line \fB6460\fP of file \fBqcustomplot\&.h\fP\&.
.SS "void QCPItemPixmap::draw (\fBQCPPainter\fP * painter)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBQCPAbstractItem\fP\&.
.PP
Definition at line \fB29349\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "QRect QCPItemPixmap::getFinalRect (bool * flippedHorz = \fC0\fP, bool * flippedVert = \fC0\fP) const\fC [protected]\fP"

.PP
Definition at line \fB29452\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "QPen QCPItemPixmap::mainPen () const\fC [protected]\fP"

.PP
Definition at line \fB29505\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "QPen QCPItemPixmap::pen () const\fC [inline]\fP"

.PP
Definition at line \fB6462\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QPixmap QCPItemPixmap::pixmap () const\fC [inline]\fP"

.PP
Definition at line \fB6458\fP of file \fBqcustomplot\&.h\fP\&.
.SS "bool QCPItemPixmap::scaled () const\fC [inline]\fP"

.PP
Definition at line \fB6459\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QPen QCPItemPixmap::selectedPen () const\fC [inline]\fP"

.PP
Definition at line \fB6463\fP of file \fBqcustomplot\&.h\fP\&.
.SS "double QCPItemPixmap::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = \fC0\fP) const\fC [virtual]\fP"
This function is used to decide whether a click hits a layerable object or not\&.
.PP
\fIpos\fP is a point in pixel coordinates on the \fBQCustomPlot\fP surface\&. This function returns the shortest pixel distance of this point to the object\&. If the object is either invisible or the distance couldn't be determined, -1\&.0 is returned\&. Further, if \fIonlySelectable\fP is true and the object is not selectable, -1\&.0 is returned, too\&.
.PP
If the object is represented not by single lines but by an area like a \fBQCPItemText\fP or the bars of a \fBQCPBars\fP plottable, a click inside the area should also be considered a hit\&. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance\&. (typically the selectionTolerance multiplied by 0\&.99)\&.
.PP
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i\&.e\&. closer than 0\&.99*selectionTolerance)\&.
.PP
The actual setting of the selection state is not done by this function\&. This is handled by the parent \fBQCustomPlot\fP when the mouseReleaseEvent occurs, and the finally selected object is notified via the \fBselectEvent/\fP deselectEvent methods\&.
.PP
\fIdetails\fP is an optional output parameter\&. Every layerable subclass may place any information in \fIdetails\fP\&. This information will be passed to \fBselectEvent\fP when the parent \fBQCustomPlot\fP decides on the basis of this selectTest call, that the object was successfully selected\&. The subsequent call to \fBselectEvent\fP will carry the \fIdetails\fP\&. This is useful for multi-part objects (like \fBQCPAxis\fP)\&. This way, a possibly complex calculation to decide which part was clicked is only done once in \fBselectTest\fP\&. The result (i\&.e\&. the actually clicked part) can then be placed in \fIdetails\fP\&. So in the subsequent \fBselectEvent\fP, the decision which part was selected doesn't have to be done a second time for a single selection operation\&.
.PP
You may pass 0 as \fIdetails\fP to indicate that you are not interested in those selection details\&.
.PP
\fBSee also\fP
.RS 4
selectEvent, deselectEvent, \fBmousePressEvent\fP, \fBwheelEvent\fP, \fBQCustomPlot::setInteractions\fP 
.RE
.PP

.PP
Implements \fBQCPAbstractItem\fP\&.
.PP
Definition at line \fB29339\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPItemPixmap::setPen (const QPen & pen)"
Sets the pen that will be used to draw a border around the pixmap\&.
.PP
\fBSee also\fP
.RS 4
\fBsetSelectedPen\fP, setBrush 
.RE
.PP

.PP
Definition at line \fB29323\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPItemPixmap::setPixmap (const QPixmap & pixmap)"
Sets the pixmap that will be displayed\&. 
.PP
Definition at line \fB29298\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPItemPixmap::setScaled (bool scaled, Qt::AspectRatioMode aspectRatioMode = \fCQt::KeepAspectRatio\fP, Qt::TransformationMode transformationMode = \fCQt::SmoothTransformation\fP)"
Sets whether the pixmap will be scaled to fit the rectangle defined by the \fItopLeft\fP and \fIbottomRight\fP positions\&. 
.PP
Definition at line \fB29310\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "void QCPItemPixmap::setSelectedPen (const QPen & pen)"
Sets the pen that will be used to draw a border around the pixmap when selected
.PP
\fBSee also\fP
.RS 4
\fBsetPen\fP, \fBsetSelected\fP 
.RE
.PP

.PP
Definition at line \fB29333\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "Qt::TransformationMode QCPItemPixmap::transformationMode () const\fC [inline]\fP"

.PP
Definition at line \fB6461\fP of file \fBqcustomplot\&.h\fP\&.
.SS "void QCPItemPixmap::updateScaledPixmap (QRect finalRect = \fCQRect()\fP, bool flipHorz = \fCfalse\fP, bool flipVert = \fCfalse\fP)\fC [protected]\fP"

.PP
Definition at line \fB29410\fP of file \fBqcustomplot\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBQCPItemAnchor\fP* const QCPItemPixmap::bottom"

.PP
Definition at line \fB6479\fP of file \fBqcustomplot\&.h\fP\&.
.SS "\fBQCPItemAnchor\fP* const QCPItemPixmap::bottomLeft"

.PP
Definition at line \fB6480\fP of file \fBqcustomplot\&.h\fP\&.
.SS "\fBQCPItemPosition\fP* const QCPItemPixmap::bottomRight"

.PP
Definition at line \fB6475\fP of file \fBqcustomplot\&.h\fP\&.
.SS "\fBQCPItemAnchor\fP* const QCPItemPixmap::left"

.PP
Definition at line \fB6481\fP of file \fBqcustomplot\&.h\fP\&.
.SS "Qt::AspectRatioMode QCPItemPixmap::mAspectRatioMode\fC [protected]\fP"

.PP
Definition at line \fB6491\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QPen QCPItemPixmap::mPen\fC [protected]\fP"

.PP
Definition at line \fB6493\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QPixmap QCPItemPixmap::mPixmap\fC [protected]\fP"

.PP
Definition at line \fB6487\fP of file \fBqcustomplot\&.h\fP\&.
.SS "bool QCPItemPixmap::mScaled\fC [protected]\fP"

.PP
Definition at line \fB6489\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QPixmap QCPItemPixmap::mScaledPixmap\fC [protected]\fP"

.PP
Definition at line \fB6488\fP of file \fBqcustomplot\&.h\fP\&.
.SS "bool QCPItemPixmap::mScaledPixmapInvalidated\fC [protected]\fP"

.PP
Definition at line \fB6490\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QPen QCPItemPixmap::mSelectedPen\fC [protected]\fP"

.PP
Definition at line \fB6493\fP of file \fBqcustomplot\&.h\fP\&.
.SS "Qt::TransformationMode QCPItemPixmap::mTransformationMode\fC [protected]\fP"

.PP
Definition at line \fB6492\fP of file \fBqcustomplot\&.h\fP\&.
.SS "\fBQCPItemAnchor\fP* const QCPItemPixmap::right"

.PP
Definition at line \fB6478\fP of file \fBqcustomplot\&.h\fP\&.
.SS "\fBQCPItemAnchor\fP* const QCPItemPixmap::top"

.PP
Definition at line \fB6476\fP of file \fBqcustomplot\&.h\fP\&.
.SS "\fBQCPItemPosition\fP* const QCPItemPixmap::topLeft"

.PP
Definition at line \fB6474\fP of file \fBqcustomplot\&.h\fP\&.
.SS "\fBQCPItemAnchor\fP* const QCPItemPixmap::topRight"

.PP
Definition at line \fB6477\fP of file \fBqcustomplot\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OmronPID from the source code\&.
