.TH "QCPStatisticalBoxData" 3 "Wed Mar 15 2023" "OmronPID" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QCPStatisticalBoxData \- Holds the data of one single data point for \fBQCPStatisticalBox\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQCPStatisticalBoxData\fP ()"
.br
.ti -1c
.RI "\fBQCPStatisticalBoxData\fP (double key, double minimum, double lowerQuartile, double median, double upperQuartile, double maximum, const QVector< double > &outliers=QVector< double >())"
.br
.ti -1c
.RI "double \fBsortKey\fP () const"
.br
.ti -1c
.RI "double \fBmainKey\fP () const"
.br
.ti -1c
.RI "double \fBmainValue\fP () const"
.br
.ti -1c
.RI "\fBQCPRange\fP \fBvalueRange\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBQCPStatisticalBoxData\fP \fBfromSortKey\fP (double \fBsortKey\fP)"
.br
.ti -1c
.RI "static bool \fBsortKeyIsMainKey\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBkey\fP"
.br
.ti -1c
.RI "double \fBminimum\fP"
.br
.ti -1c
.RI "double \fBlowerQuartile\fP"
.br
.ti -1c
.RI "double \fBmedian\fP"
.br
.ti -1c
.RI "double \fBupperQuartile\fP"
.br
.ti -1c
.RI "double \fBmaximum\fP"
.br
.ti -1c
.RI "QVector< double > \fBoutliers\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds the data of one single data point for \fBQCPStatisticalBox\fP\&. 

The stored data is:
.PP
.PD 0
.IP "\(bu" 2
\fIkey:\fP coordinate on the key axis of this data point (this is the \fImainKey\fP and the \fIsortKey\fP)
.PP
.PD 0
.IP "\(bu" 2
\fIminimum:\fP the position of the lower whisker, typically the minimum measurement of the sample that's not considered an outlier\&.
.PP
.PD 0
.IP "\(bu" 2
\fIlowerQuartile:\fP the lower end of the box\&. The lower and the upper quartiles are the two statistical quartiles around the median of the sample, they should contain 50% of the sample data\&.
.PP
.PD 0
.IP "\(bu" 2
\fImedian:\fP the value of the median mark inside the quartile box\&. The median separates the sample data in half (50% of the sample data is below/above the median)\&. (This is the \fImainValue\fP)
.PP
.PD 0
.IP "\(bu" 2
\fIupperQuartile:\fP the upper end of the box\&. The lower and the upper quartiles are the two statistical quartiles around the median of the sample, they should contain 50% of the sample data\&.
.PP
.PD 0
.IP "\(bu" 2
\fImaximum:\fP the position of the upper whisker, typically the maximum measurement of the sample that's not considered an outlier\&.
.PP
.PD 0
.IP "\(bu" 2
\fIoutliers:\fP a QVector of outlier values that will be drawn as scatter points at the \fIkey\fP coordinate of this data point (see \fBQCPStatisticalBox::setOutlierStyle\fP)
.PP
The container for storing multiple data points is \fBQCPStatisticalBoxDataContainer\fP\&. It is a typedef for \fBQCPDataContainer\fP with \fBQCPStatisticalBoxData\fP as the DataType template parameter\&. See the documentation there for an explanation regarding the data type's generic methods\&.
.PP
\fBSee also\fP
.RS 4
QCPStatisticalBoxDataContainer 
.RE
.PP

.PP
Definition at line \fB5563\fP of file \fBqcustomplot\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QCPStatisticalBoxData::QCPStatisticalBoxData ()"
Constructs a data point with key and all values set to zero\&. 
.PP
Definition at line \fB24366\fP of file \fBqcustomplot\&.cpp\fP\&.
.SS "QCPStatisticalBoxData::QCPStatisticalBoxData (double key, double minimum, double lowerQuartile, double median, double upperQuartile, double maximum, const QVector< double > & outliers = \fCQVector<double>()\fP)"
Constructs a data point with the specified \fIkey\fP, \fIminimum\fP, \fIlowerQuartile\fP, \fImedian\fP, \fIupperQuartile\fP, \fImaximum\fP and optionally a number of \fIoutliers\fP\&. 
.PP
Definition at line \fB24380\fP of file \fBqcustomplot\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBQCPStatisticalBoxData\fP QCPStatisticalBoxData::fromSortKey (double sortKey)\fC [inline]\fP, \fC [static]\fP"
Returns a data point with the specified \fIsortKey\fP\&. All other members are set to zero\&.
.PP
For a general explanation of what this method is good for in the context of the data container, see the documentation of \fBQCPDataContainer\fP\&. 
.PP
Definition at line \fB5570\fP of file \fBqcustomplot\&.h\fP\&.
.SS "double QCPStatisticalBoxData::mainKey () const\fC [inline]\fP"
Returns the \fIkey\fP member of this data point\&.
.PP
For a general explanation of what this method is good for in the context of the data container, see the documentation of \fBQCPDataContainer\fP\&. 
.PP
Definition at line \fB5573\fP of file \fBqcustomplot\&.h\fP\&.
.SS "double QCPStatisticalBoxData::mainValue () const\fC [inline]\fP"
Returns the \fImedian\fP member of this data point\&.
.PP
For a general explanation of what this method is good for in the context of the data container, see the documentation of \fBQCPDataContainer\fP\&. 
.PP
Definition at line \fB5574\fP of file \fBqcustomplot\&.h\fP\&.
.SS "double QCPStatisticalBoxData::sortKey () const\fC [inline]\fP"
Returns the \fIkey\fP member of this data point\&.
.PP
For a general explanation of what this method is good for in the context of the data container, see the documentation of \fBQCPDataContainer\fP\&. 
.PP
Definition at line \fB5569\fP of file \fBqcustomplot\&.h\fP\&.
.SS "static static bool QCPStatisticalBoxData::sortKeyIsMainKey ()\fC [inline]\fP, \fC [static]\fP"
Since the member \fIkey\fP is both the data point key coordinate and the data ordering parameter, this method returns true\&.
.PP
For a general explanation of what this method is good for in the context of the data container, see the documentation of \fBQCPDataContainer\fP\&. 
.PP
Definition at line \fB5571\fP of file \fBqcustomplot\&.h\fP\&.
.SS "\fBQCPRange\fP QCPStatisticalBoxData::valueRange () const\fC [inline]\fP"
Returns a \fBQCPRange\fP spanning from the \fIminimum\fP to the \fImaximum\fP member of this statistical box data point, possibly further expanded by outliers\&.
.PP
For a general explanation of what this method is good for in the context of the data container, see the documentation of \fBQCPDataContainer\fP\&. 
.PP
Definition at line \fB5576\fP of file \fBqcustomplot\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double QCPStatisticalBoxData::key"

.PP
Definition at line \fB5584\fP of file \fBqcustomplot\&.h\fP\&.
.SS "double QCPStatisticalBoxData::lowerQuartile"

.PP
Definition at line \fB5584\fP of file \fBqcustomplot\&.h\fP\&.
.SS "double QCPStatisticalBoxData::maximum"

.PP
Definition at line \fB5584\fP of file \fBqcustomplot\&.h\fP\&.
.SS "double QCPStatisticalBoxData::median"

.PP
Definition at line \fB5584\fP of file \fBqcustomplot\&.h\fP\&.
.SS "double QCPStatisticalBoxData::minimum"

.PP
Definition at line \fB5584\fP of file \fBqcustomplot\&.h\fP\&.
.SS "QVector<double> QCPStatisticalBoxData::outliers"

.PP
Definition at line \fB5585\fP of file \fBqcustomplot\&.h\fP\&.
.SS "double QCPStatisticalBoxData::upperQuartile"

.PP
Definition at line \fB5584\fP of file \fBqcustomplot\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OmronPID from the source code\&.
